### ISSUE TITLE
Really hard to configure

### ISSUE THREAD

**Issue by haf-afa** [kiali/kiali#2736]
**General remarks**

It's really hard to configure Kiali correctly.

1. The config structure is mostly undocumented
2. It's mostly undocumented how auth works; e.g. use oauth2_proxy and insert the public URIs for prom, grafana, jaeger, and the UI throws a fit and can't access anything, despite the cookie set by oauth2_proxy being valid for all those
3. Crashes inside Kiali:

```
kiali-5d88d778f7-zw4v5 kiali E0505 09:58:46.319053       1 graph.go:87] Get "/api/v1/query?query=round%28sum%28rate%28istio_requests_total%7Breporter%3D%22destination%22%2Csource_workload%3D%22unknown%22%2Cdestination_workload_namespace%3D%22fou%22%7D+%5B60s%5D%29%29+by+%28source_workload_namespace%2Csource_workload%2Csource_canonical_service%2Csource_canonical_revision%2Cdestination_service_namespace%2Cdestination_service%2Cdestination_service_name%2Cdestination_workload_namespace%2Cdestination_workload%2Cdestination_canonical_service%2Cdestination_canonical_revision%2Crequest_protocol%2Cresponse_code%2Cgrpc_response_status%2Cresponse_flags%29%2C0.001%29&time=2020-05-05T09%3A58%3A46Z": unsupported protocol scheme "": goroutine 310 [running]:
kiali-5d88d778f7-zw4v5 kiali runtime/debug.Stack(0xc001372000, 0x28e, 0xc00073a200)
kiali-5d88d778f7-zw4v5 kiali 	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
kiali-5d88d778f7-zw4v5 kiali github.com/kiali/kiali/handlers.handlePanic(0x1676a00, 0xc0003d49a0)
kiali-5d88d778f7-zw4v5 kiali 	/home/jenkins/agent/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/handlers/graph.go:86 +0x155
kiali-5d88d778f7-zw4v5 kiali panic(0x122fde0, 0xc00073a200)
kiali-5d88d778f7-zw4v5 kiali 	/usr/local/go/src/runtime/panic.go:967 +0x15d
kiali-5d88d778f7-zw4v5 kiali github.com/kiali/kiali/graph.CheckError(0x1641c00, 0xc0007961b0)
kiali-5d88d778f7-zw4v5 kiali 	/home/jenkins/agent/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/graph/util.go:38 +0x9c
kiali-5d88d778f7-zw4v5 kiali github.com/kiali/kiali/graph/telemetry/istio.promQuery(0xc000f15c00, 0x1ea, 0x0, 0xed6432fd6, 0x205b4a0, 0x168c720, 0xc0007fb5a0, 0x0, 0x0, 0x0)
kiali-5d88d778f7-zw4v5 kiali 	/home/jenkins/agent/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/graph/telemetry/istio/istio.go:749 +0x433
kiali-5d88d778f7-zw4v5 kiali github.com/kiali/kiali/graph/telemetry/istio.buildNamespaceTrafficMap(0xc0006780a7, 0x3, 0xc00117bc50, 0x0, 0xc00147c9c0, 0x4, 0x4, 0x1, 0xc00117bb60, 0xdf8475800, ...)
kiali-5d88d778f7-zw4v5 kiali 	/home/jenkins/agent/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/graph/telemetry/istio/istio.go:109 +0x44e
kiali-5d88d778f7-zw4v5 kiali github.com/kiali/kiali/graph/telemetry/istio.BuildNamespacesTrafficMap(0xc00117bc50, 0x0, 0xc00147c9c0, 0x4, 0x4, 0x1, 0xc00117bb60, 0xdf8475800, 0xc000678037, 0xc, ...)
kiali-5d88d778f7-zw4v5 kiali 	/home/jenkins/agent/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/graph/telemetry/istio/istio.go:59 +0x46e
kiali-5d88d778f7-zw4v5 kiali github.com/kiali/kiali/graph/api.graphNamespacesIstio(0xc000ffbe00, 0xc00117be90, 0x143dc86, 0x9, 0x143b5b9, 0x5, 0xc000678064, 0x3, 0xdf8475800, 0xc000678037, ...)
kiali-5d88d778f7-zw4v5 kiali 	/home/jenkins/agent/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/graph/api/api.go:44 +0xb8
kiali-5d88d778f7-zw4v5 kiali github.com/kiali/kiali/graph/api.GraphNamespaces(0xc000ffbe00, 0x143dc86, 0x9, 0x143b5b9, 0x5, 0xc000678064, 0x3, 0xdf8475800, 0xc000678037, 0xc, ...)
kiali-5d88d778f7-zw4v5 kiali 	/home/jenkins/agent/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/graph/api/api.go:26 +0x173
kiali-5d88d778f7-zw4v5 kiali github.com/kiali/kiali/handlers.GraphNamespaces(0x1676a00, 0xc0003d49a0, 0xc000d9a800)
kiali-5d88d778f7-zw4v5 kiali 	/home/jenkins/agent/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/handlers/graph.go:51 +0x136
kiali-5d88d778f7-zw4v5 kiali net/http.HandlerFunc.ServeHTTP(0x14d6140, 0x1676a00, 0xc0003d49a0, 0xc000d9a800)
kiali-5d88d778f7-zw4v5 kiali 	/usr/local/go/src/net/http/server.go:2012 +0x44
kiali-5d88d778f7-zw4v5 kiali github.com/kiali/kiali/handlers.AuthenticationHandler.Handle.func1(0x1676a00, 0xc0003d49a0, 0xc000d9a700)
kiali-5d88d778f7-zw4v5 kiali 	/home/jenkins/agent/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/handlers/authentication.go:498 +0x203
kiali-5d88d778f7-zw4v5 kiali net/http.HandlerFunc.ServeHTTP(0xc00045c2a0, 0x1676a00, 0xc0003d49a0, 0xc000d9a700)
kiali-5d88d778f7-zw4v5 kiali 	/usr/local/go/src/net/http/server.go:2012 +0x44
kiali-5d88d778f7-zw4v5 kiali github.com/kiali/kiali/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc000380180, 0x1676a00, 0xc0003d49a0, 0xc0002fca00)
kiali-5d88d778f7-zw4v5 kiali 	/home/jenkins/agent/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
kiali-5d88d778f7-zw4v5 kiali github.com/kiali/kiali/vendor/github.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1(0x1676640, 0xc0002061c0, 0xc0002fca00)
kiali-5d88d778f7-zw4v5 kiali 	/home/jenkins/agent/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/vendor/github.com/NYTimes/gziphandler/gzip.go:336 +0x211
kiali-5d88d778f7-zw4v5 kiali net/http.HandlerFunc.ServeHTTP(0xc000499350, 0x1676640, 0xc0002061c0, 0xc0002fca00)
kiali-5d88d778f7-zw4v5 kiali 	/usr/local/go/src/net/http/server.go:2012 +0x44
kiali-5d88d778f7-zw4v5 kiali net/http.(*ServeMux).ServeHTTP(0xc00041b800, 0x1676640, 0xc0002061c0, 0xc0002fca00)
kiali-5d88d778f7-zw4v5 kiali 	/usr/local/go/src/net/http/server.go:2387 +0x1a5
kiali-5d88d778f7-zw4v5 kiali net/http.serverHandler.ServeHTTP(0xc0004be000, 0x1676640, 0xc0002061c0, 0xc0002fca00)
kiali-5d88d778f7-zw4v5 kiali 	/usr/local/go/src/net/http/server.go:2807 +0xa3
kiali-5d88d778f7-zw4v5 kiali net/http.(*conn).serve(0xc0004a3ea0, 0x167ce80, 0xc000317d40)
kiali-5d88d778f7-zw4v5 kiali 	/usr/local/go/src/net/http/server.go:1895 +0x86c
kiali-5d88d778f7-zw4v5 kiali created by net/http.(*Server).Serve
kiali-5d88d778f7-zw4v5 kiali 	/usr/local/go/src/net/http/server.go:2933 +0x35c
kiali-5d88d778f7-zw4v5 kiali E0505 09:59:01.046958       1 graph.go:87] Get "/api/v1/query?query=round%28sum%28rate%28istio_requests_total%7Breporter%3D%22destination%22%2Csource_workload%3D%22unknown%22%2Cdestination_workload_namespace%3D%22fou%22%7D+%5B60s%5D%29%29+by+%28source_workload_namespace%2Csource_workload%2Csource_canonical_service%2Csource_canonical_revision%2Cdestination_service_namespace%2Cdestination_service%2Cdestination_service_name%2Cdestination_workload_namespace%2Cdestination_workload%2Cdestination_canonical_service%2Cdestination_canonical_revision%2Crequest_protocol%2Cresponse_code%2Cgrpc_response_status%2Cresponse_flags%29%2C0.001%29&time=2020-05-05T09%3A59%3A01Z": unsupported protocol scheme "": goroutine 310 [running]:
kiali-5d88d778f7-zw4v5 kiali runtime/debug.Stack(0xc001372b00, 0x28e, 0xc0007282a0)
kiali-5d88d778f7-zw4v5 kiali 	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
kiali-5d88d778f7-zw4v5 kiali github.com/kiali/kiali/handlers.handlePanic(0x1676a00, 0xc0003d4f50)
kiali-5d88d778f7-zw4v5 kiali 	/home/jenkins/agent/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/handlers/graph.go:86 +0x155
kiali-5d88d778f7-zw4v5 kiali panic(0x122fde0, 0xc0007282a0)
kiali-5d88d778f7-zw4v5 kiali 	/usr/local/go/src/runtime/panic.go:967 +0x15d
kiali-5d88d778f7-zw4v5 kiali github.com/kiali/kiali/graph.CheckError(0x1641c00, 0xc00116eb10)
kiali-5d88d778f7-zw4v5 kiali 	/home/jenkins/agent/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/graph/util.go:38 +0x9c
kiali-5d88d778f7-zw4v5 kiali github.com/kiali/kiali/graph/telemetry/istio.promQuery(0xc000974400, 0x1ea, 0x0, 0xed6432fe5, 0x205b4a0, 0x168c720, 0xc000994120, 0x0, 0x0, 0x0)
kiali-5d88d778f7-zw4v5 kiali 	/home/jenkins/agent/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/graph/telemetry/istio/istio.go:749 +0x433
kiali-5d88d778f7-zw4v5 kiali github.com/kiali/kiali/graph/telemetry/istio.buildNamespaceTrafficMap(0xc0006786a7, 0x3, 0xc00116e6f0, 0x0, 0xc00178f9c0, 0x4, 0x4, 0x1, 0xc000797f80, 0xdf8475800, ...)
kiali-5d88d778f7-zw4v5 kiali 	/home/jenkins/agent/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/graph/telemetry/istio/istio.go:109 +0x44e
kiali-5d88d778f7-zw4v5 kiali github.com/kiali/kiali/graph/telemetry/istio.BuildNamespacesTrafficMap(0xc00116e6f0, 0x0, 0xc00178f9c0, 0x4, 0x4, 0x1, 0xc000797f80, 0xdf8475800, 0xc000678637, 0xc, ...)
kiali-5d88d778f7-zw4v5 kiali 	/home/jenkins/agent/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/graph/telemetry/istio/istio.go:59 +0x46e
kiali-5d88d778f7-zw4v5 kiali github.com/kiali/kiali/graph/api.graphNamespacesIstio(0xc000c78c00, 0xc00116e7b0, 0x143dc86, 0x9, 0x143b5b9, 0x5, 0xc000678664, 0x3, 0xdf8475800, 0xc000678637, ...)
kiali-5d88d778f7-zw4v5 kiali 	/home/jenkins/agent/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/graph/api/api.go:44 +0xb8
kiali-5d88d778f7-zw4v5 kiali github.com/kiali/kiali/graph/api.GraphNamespaces(0xc000c78c00, 0x143dc86, 0x9, 0x143b5b9, 0x5, 0xc000678664, 0x3, 0xdf8475800, 0xc000678637, 0xc, ...)
kiali-5d88d778f7-zw4v5 kiali 	/home/jenkins/agent/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/graph/api/api.go:26 +0x173
kiali-5d88d778f7-zw4v5 kiali github.com/kiali/kiali/handlers.GraphNamespaces(0x1676a00, 0xc0003d4f50, 0xc000c65100)
kiali-5d88d778f7-zw4v5 kiali 	/home/jenkins/agent/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/handlers/graph.go:51 +0x136
kiali-5d88d778f7-zw4v5 kiali net/http.HandlerFunc.ServeHTTP(0x14d6140, 0x1676a00, 0xc0003d4f50, 0xc000c65100)
kiali-5d88d778f7-zw4v5 kiali 	/usr/local/go/src/net/http/server.go:2012 +0x44
kiali-5d88d778f7-zw4v5 kiali github.com/kiali/kiali/handlers.AuthenticationHandler.Handle.func1(0x1676a00, 0xc0003d4f50, 0xc000c65000)
kiali-5d88d778f7-zw4v5 kiali 	/home/jenkins/agent/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/handlers/authentication.go:498 +0x203
kiali-5d88d778f7-zw4v5 kiali net/http.HandlerFunc.ServeHTTP(0xc00045c2a0, 0x1676a00, 0xc0003d4f50, 0xc000c65000)
kiali-5d88d778f7-zw4v5 kiali 	/usr/local/go/src/net/http/server.go:2012 +0x44
kiali-5d88d778f7-zw4v5 kiali github.com/kiali/kiali/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc000380180, 0x1676a00, 0xc0003d4f50, 0xc000d9ac00)
kiali-5d88d778f7-zw4v5 kiali 	/home/jenkins/agent/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
kiali-5d88d778f7-zw4v5 kiali github.com/kiali/kiali/vendor/github.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1(0x1676640, 0xc0004be7e0, 0xc000d9ac00)
kiali-5d88d778f7-zw4v5 kiali 	/home/jenkins/agent/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/vendor/github.com/NYTimes/gziphandler/gzip.go:336 +0x211
kiali-5d88d778f7-zw4v5 kiali net/http.HandlerFunc.ServeHTTP(0xc000499350, 0x1676640, 0xc0004be7e0, 0xc000d9ac00)
kiali-5d88d778f7-zw4v5 kiali 	/usr/local/go/src/net/http/server.go:2012 +0x44
kiali-5d88d778f7-zw4v5 kiali net/http.(*ServeMux).ServeHTTP(0xc00041b800, 0x1676640, 0xc0004be7e0, 0xc000d9ac00)
kiali-5d88d778f7-zw4v5 kiali 	/usr/local/go/src/net/http/server.go:2387 +0x1a5
kiali-5d88d778f7-zw4v5 kiali net/http.serverHandler.ServeHTTP(0xc0004be000, 0x1676640, 0xc0004be7e0, 0xc000d9ac00)
kiali-5d88d778f7-zw4v5 kiali 	/usr/local/go/src/net/http/server.go:2807 +0xa3
kiali-5d88d778f7-zw4v5 kiali net/http.(*conn).serve(0xc0004a3ea0, 0x167ce80, 0xc000317d40)
kiali-5d88d778f7-zw4v5 kiali 	/usr/local/go/src/net/http/server.go:1895 +0x86c
kiali-5d88d778f7-zw4v5 kiali created by net/http.(*Server).Serve
kiali-5d88d778f7-zw4v5 kiali 	/usr/local/go/src/net/http/server.go:2933 +0x35c
```
4. Lots of errors like `kiali-5d88d778f7-2t7tt kiali E0505 09:58:45.519716       1 errors.go:21] Error while fetching app health: Get "/api/v1/query?query=rate%28istio_requests_total%7Bdestination_service_namespace%3D%22monitoring%22%2Csource_workload_namespace%21%3D%22monitoring%22%7D%5B60s%5D%29&time=2020-05-05T09%3A58%3A45.490267744Z": unsupported protocol scheme ""`, despite the configuration having no 'scheme' field. Also, the error message doesn't say which service it's calling out to (is it prom? grafana? jaeger?)

**Describe the bug**

Start kiali with this config:

```yaml
istio_component_namespaces:
  grafana: monitoring
  tracing: monitoring
  pilot: istio-system
  prometheus: monitoring

istio_namespace: istio-system

auth:
  strategy: anonymous

deployment:
  accessible_namespaces: ['**']

login_token:
  signing_key: "nMAQQ5eHPG"

server:
  port: 20001
  web_root: /kiali

external_services:
  istio:
    url_service_version: http://istio-pilot.istio-system:8080/version
  tracing:
    url:
    in_cluster_url: http://jaeger-query.monitoring:16686
  grafana:
    url:
    in_cluster_url: http://grafana.monitoring:3000
  prometheus:
    url:
    in_cluster_url: http://prometheus.monitoring:9090
```

<img width="1295" alt="image" src="https://user-images.githubusercontent.com/56340843/81055414-f009d100-8ec8-11ea-884a-e072c2d0fcf4.png">
<img width="515" alt="image" src="https://user-images.githubusercontent.com/56340843/81055463-fef08380-8ec8-11ea-918f-615066335034.png">
<img width="595" alt="image" src="https://user-images.githubusercontent.com/56340843/81055469-031ca100-8ec9-11ea-98c0-3c008feea20d.png">
<img width="360" alt="image" src="https://user-images.githubusercontent.com/56340843/81055477-06179180-8ec9-11ea-9969-0a114aee57a0.png">
<img width="344" alt="image" src="https://user-images.githubusercontent.com/56340843/81055498-116abd00-8ec9-11ea-9f3b-d4042d85520b.png">
<img width="551" alt="image" src="https://user-images.githubusercontent.com/56340843/81055503-1465ad80-8ec9-11ea-9680-15aeff7b59d6.png">

**Versions used**
Kiali: image: quay.io/kiali/kiali:v1.15
Istio: 1.5.2
Kubernetes flavour and version: GKE 1.15.x

**To Reproduce**
1. Template istio's demo profile
2. Move jaeger, grafana and prometheus to the outside of istio-system, like they should be
3. Set up oauth2_proxy with an envoy filter and with google identities as the OIDC provider
4. Set up TLS / https for the domain you host kiali on
5. Set auth=anonymous
6.a. Don't configure "url" for all of grafana, jaeger, prom — get a bunch of errors like described above
6.b. Do configure "url" for all of the above — get a bunch of errors but in the browser instead

**Expected behavior**
For Kiali to be configurable. Docs and logs from the server focuses on operators and openshift, instead of describing the product's configuration. It's hard/impossible to debug without going through and reading the Kiali code; e.g. the config file requires you to read the serialisation code in https://github.com/kiali/kiali/blob/master/config/config.go

**Comment by lucasponce** [comment]
Thanks for the issue and feedback @haf-afa 

Kiali's primary config method is through the kiali operator which config is well described here:
https://github.com/kiali/kiali-operator/blob/master/deploy/kiali/kiali_cr.yaml

Note that Kiali Operator can be deployed on any platform and most of our dev team uses minikube as primary development platform to be sure all Kiali changes are full kubernetes compatible.

But it's good to understand these scenarios, I appreciate you take the time to report it.
It will help us to improve the doc.

**Comment by jotak** [comment]
@haf-afa there's no `in_cluster_url` for the prometheus config, and I think most of the problems you see come from there. See https://github.com/kiali/kiali-operator/blob/master/deploy/kiali/kiali_cr.yaml#L446-L463

So your prometheus URL should be set on the `url` field.

That being said, I'm in favor of having all of our config documentation on kiali.io instead of as yaml comments, and better structured, that would probably help the user experience.

**Comment by israel-hdez** [comment]
Related to #2651

**Comment by haf-afa** [comment]
@jotak So the `url` field for prometheus should be the internally accessible URL?

**Comment by lucasponce** [comment]
As part of the #2251 some of the topics discussed in this issue should be addressed.

**Comment by jshaughn** [comment]
Those error reported seem like bad handling of a bad prometheus config.  We should test more thoroughly the handling of a missing prometheus.

**Comment by lucasponce** [comment]
Kiali has improved the installation and configuration process adding more documentation in:

https://kiali.io/documentation/latest/quick-start/
https://kiali.io/documentation/latest/installation-guide/

Also adding more content in the FAQ to cover potential gaps in the config docs in a quickly manner:
https://kiali.io/documentation/latest/faq/

Probably it's not complete and things can improve but it's in the good direction compared when this issue was opened.

Also, there is a new discussions area:
https://github.com/kiali/kiali/discussions

Where community can discuss potential ideas that not necessarily means a new feature but knowledge sharing.

As there is not a specific task on this side I'm going to close this one.

Please, feel free to re-open it or create a new one in case something it's missing.

Thank you.
