### ISSUE TITLE
Error fetching spans on idle workloads

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#3233]
Running an experiment I scale to 0 a workload and I got an internal error while getting details in Kiali:

![image](https://user-images.githubusercontent.com/1662329/93878553-8e60cc80-fcda-11ea-9244-c7affe0b2fa5.png)

**Comment by aljesusg** [comment]
I can't replicate this

![Screenshot from 2020-09-22 14-33-41](https://user-images.githubusercontent.com/3019213/93882604-ba7f4c00-fce0-11ea-8df5-30637a8d8822.png)

In fact the call to spans when there is not pods return []

jaeger api when we fetch a traces of a service that not exist this return

```json
{"data":[],"total":0,"limit":0,"offset":0,"errors":null}
```

so it seems that this error is related with another thing @lucasponce, maybe jaeger crashed because it says internal server error, I'm going to make another tests to be sure 

cc @jotak

**Comment by jotak** [comment]
@lucasponce perhaps you have more information in kiali server logs?

**Comment by lucasponce** [comment]
I get this details from the browser, I'm running from localhost.
![image](https://user-images.githubusercontent.com/1662329/93886573-e6510080-fce5-11ea-8539-669853e16213.png)

I'm not using the normal bookinfo, but a different example:

```
kubectl apply -f https://iter8.tools/tutorials/namespace.yaml
kubectl --namespace bookinfo-iter8 apply -f https://iter8.tools/tutorials/bookinfo-tutorial.yaml
kubectl --namespace bookinfo-iter8 apply -f https://iter8.tools/tutorials/reviews-v3.yaml
```

And try to set replica to 0

![image](https://user-images.githubusercontent.com/1662329/93886872-3b8d1200-fce6-11ea-871d-4c8ff3c8753c.png)


Jaeger traces tab shows no errors, but this info:

![image](https://user-images.githubusercontent.com/1662329/93886949-5790b380-fce6-11ea-8df1-912ee8283a11.png)


But the Metrics tabs fails with a similar like this:

![image](https://user-images.githubusercontent.com/1662329/93887025-70996480-fce6-11ea-875e-04499094586f.png)

Kiali logs are clean, it may be something else, I don't know I haven't started to debug, just to describe the problem.

**Comment by lucasponce** [comment]
```
GET http://admin:admin@localhost:8000/api/namespaces/bookinfo-iter8/workloads/reviews-v2/spans?startMicros=1600780418154000
```

```
I0922 15:26:39.219387   95340 istio.go:363] TRACE: meshConfig: accessLogFile: /dev/stdout
defaultConfig:
  discoveryAddress: istiod.istio-system.svc:15012
  proxyMetadata:
    DNS_AGENT: ""
  tracing:
    zipkin:
      address: zipkin.istio-system:9411
disableMixerHttpReports: true
enablePrometheusMerge: true
rootNamespace: istio-system
trustDomain: cluster.local
I0922 15:26:39.233205   95340 jaeger.go:236] TRACE: Found 0 spans in the 100 traces for app reviews
2020/09/22 15:26:39 http: panic serving 127.0.0.1:37014: runtime error: index out of range [0] with length 0
goroutine 724 [running]:
net/http.(*conn).serve.func1(0xc000162dc0)
        /home/lponce/Software/go/src/net/http/server.go:1800 +0x139
panic(0x13d9b00, 0xc00042b020)
        /home/lponce/Software/go/src/runtime/panic.go:975 +0x3e3
github.com/kiali/kiali/business.findRelevantSpans(0x16c9c40, 0xc0003b2780, 0x205c860, 0x0, 0x0, 0xc000b84164, 0xe, 0xc000594c40, 0x7, 0xc000b8419a, ...)
        /home/lponce/Projects/gopath/src/github.com/kiali/kiali/business/jaeger.go:258 +0xadd
github.com/kiali/kiali/business.(*JaegerService).getFilteredSpans(0xc00074a430, 0xc000b84164, 0xe, 0xc000594c40, 0x7, 0xc000b8419a, 0x10, 0x0, 0x0, 0x0, ...)
        /home/lponce/Projects/gopath/src/github.com/kiali/kiali/business/jaeger.go:50 +0x29c
github.com/kiali/kiali/business.(*JaegerService).GetWorkloadSpans(0xc00074a430, 0xc000b84164, 0xe, 0xc000b8417d, 0xa, 0xc000b8419a, 0x10, 0x0, 0x0, 0x0, ...)
        /home/lponce/Projects/gopath/src/github.com/kiali/kiali/business/jaeger.go:81 +0x1a6
github.com/kiali/kiali/handlers.WorkloadSpans(0x16d5a40, 0xc0001af1f0, 0xc0001fea00)
        /home/lponce/Projects/gopath/src/github.com/kiali/kiali/handlers/jaeger.go:219 +0x215
net/http.HandlerFunc.ServeHTTP(0x152dff0, 0x16d5a40, 0xc0001af1f0, 0xc0001fea00)
        /home/lponce/Software/go/src/net/http/server.go:2041 +0x44
github.com/kiali/kiali/handlers.AuthenticationHandler.Handle.func1(0x16d5a40, 0xc0001af1f0, 0xc0001fe700)
        /home/lponce/Projects/gopath/src/github.com/kiali/kiali/handlers/authentication.go:465 +0x200
net/http.HandlerFunc.ServeHTTP(0xc00034d8c0, 0x16d5a40, 0xc0001af1f0, 0xc0001fe700)
        /home/lponce/Software/go/src/net/http/server.go:2041 +0x44
github.com/kiali/kiali/server.plainHttpMiddleware.func1(0x16d5a40, 0xc0001af1f0, 0xc0001fe700)
        /home/lponce/Projects/gopath/src/github.com/kiali/kiali/server/server.go:124 +0x6c
net/http.HandlerFunc.ServeHTTP(0xc000968e20, 0x16d5a40, 0xc0001af1f0, 0xc0001fe700)
        /home/lponce/Software/go/src/net/http/server.go:2041 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000209140, 0x16d5a40, 0xc0001af1f0, 0xc0001fe100)
        /home/lponce/Projects/gopath/pkg/mod/github.com/gorilla/mux@v1.7.4/mux.go:210 +0xe2
github.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1(0x16d5680, 0xc000170620, 0xc0001fe100)
        /home/lponce/Projects/gopath/pkg/mod/github.com/!n!y!times/gziphandler@v1.1.1/gzip.go:336 +0x211
net/http.HandlerFunc.ServeHTTP(0xc000440600, 0x16d5680, 0xc000170620, 0xc0001fe100)
        /home/lponce/Software/go/src/net/http/server.go:2041 +0x44
net/http.(*ServeMux).ServeHTTP(0xc000369800, 0x16d5680, 0xc000170620, 0xc0001fe100)
        /home/lponce/Software/go/src/net/http/server.go:2416 +0x1a5
net/http.serverHandler.ServeHTTP(0xc0001702a0, 0x16d5680, 0xc000170620, 0xc0001fe100)
        /home/lponce/Software/go/src/net/http/server.go:2836 +0xa3
net/http.(*conn).serve(0xc000162dc0, 0x16d8c40, 0xc00063f680)
        /home/lponce/Software/go/src/net/http/server.go:1924 +0x86c
created by net/http.(*Server).Serve
        /home/lponce/Software/go/src/net/http/server.go:2962 +0x35c


```

**Comment by hhovsepy** [comment]
I see different issue on my environment for that particular namespace:
![Screenshot from 2020-09-22 19-09-04](https://user-images.githubusercontent.com/604313/93914680-296f9b80-fd07-11ea-80fa-034baaa61e55.png)

**Comment by lucasponce** [comment]
@hhovsepy interesting, I'm going to check the PR with the example, perhaps I missed to post some detail of my env

**Comment by lucasponce** [comment]
@hhovsepy I tweaked the Istio config, as I have at same time the bookinfo and bookinfo-iter8 exposed through the gateway.
I created a couple of different fake host names "bookinfo.<namespace>.com" to expose the two bookinfo examples.

Perhaps that's what you saw this new error.

I've tested the patch locally and it works as expected.
