### ISSUE TITLE
panic in server , openid code

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#3248]
I'm sending some requests I do not expect to give me access via curl. Even though I know I should not have access because I did not log in via openID, we should not panic the server. We should fix this by performing necessary checks (I assume there is a nil here somewhere that we need to check):

```
2020/09/24 11:44:29 http: panic serving 127.0.0.1:58904: runtime error: invalid memory address or nil pointer dereference
goroutine 385 [running]:
net/http.(*conn).serve.func1(0xc00033afa0)
	/home/jmazzite/bin/go-install/go/src/net/http/server.go:1800 +0x139
panic(0x12f2700, 0x200fb10)
	/home/jmazzite/bin/go-install/go/src/runtime/panic.go:975 +0x3e3
github.com/kiali/kiali/handlers.performOpenIdAuthentication(0x16cd1e0, 0xc000180a80, 0xc00025fd00, 0xc000158380)
	/home/jmazzite/source/kiali/kiali/src/github.com/kiali/kiali/handlers/authentication.go:160 +0x913
github.com/kiali/kiali/handlers.Authenticate(0x16cd1e0, 0xc000180a80, 0xc00025fd00)
	/home/jmazzite/source/kiali/kiali/src/github.com/kiali/kiali/handlers/authentication.go:488 +0x203
net/http.HandlerFunc.ServeHTTP(0x1526800, 0x16cd1e0, 0xc000180a80, 0xc00025fd00)
	/home/jmazzite/bin/go-install/go/src/net/http/server.go:2041 +0x44
github.com/kiali/kiali/handlers.AuthenticationHandler.HandleUnauthenticated.func1(0x16cd1e0, 0xc000180a80, 0xc00025fc00)
	/home/jmazzite/source/kiali/kiali/src/github.com/kiali/kiali/handlers/authentication.go:478 +0x166
net/http.HandlerFunc.ServeHTTP(0xc00036d680, 0x16cd1e0, 0xc000180a80, 0xc00025fc00)
	/home/jmazzite/bin/go-install/go/src/net/http/server.go:2041 +0x44
github.com/kiali/kiali/routing.metricHandler.func1(0x16cd1e0, 0xc000180a80, 0xc00025fc00)
	/home/jmazzite/source/kiali/kiali/src/github.com/kiali/kiali/routing/router.go:89 +0xa3
net/http.HandlerFunc.ServeHTTP(0xc0003a2180, 0x16cd1e0, 0xc000180a80, 0xc00025fc00)
	/home/jmazzite/bin/go-install/go/src/net/http/server.go:2041 +0x44
github.com/kiali/kiali/server.plainHttpMiddleware.func1(0x16cd1e0, 0xc000180a80, 0xc00025fc00)
	/home/jmazzite/source/kiali/kiali/src/github.com/kiali/kiali/server/server.go:124 +0x6c
net/http.HandlerFunc.ServeHTTP(0xc0003c31e0, 0x16cd1e0, 0xc000180a80, 0xc00025fc00)
	/home/jmazzite/bin/go-install/go/src/net/http/server.go:2041 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc00029b140, 0x16cd1e0, 0xc000180a80, 0xc00025fa00)
	/home/jmazzite/source/kiali/kiali/pkg/mod/github.com/gorilla/mux@v1.7.4/mux.go:210 +0xe2
github.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1(0x16cd1e0, 0xc000180a80, 0xc00025fa00)
	/home/jmazzite/source/kiali/kiali/pkg/mod/github.com/!n!y!times/gziphandler@v1.1.1/gzip.go:342 +0x2f1
net/http.HandlerFunc.ServeHTTP(0xc0004c65d0, 0x16cd1e0, 0xc000180a80, 0xc00025fa00)
	/home/jmazzite/bin/go-install/go/src/net/http/server.go:2041 +0x44
net/http.(*ServeMux).ServeHTTP(0xc00047ab00, 0x16cd1e0, 0xc000180a80, 0xc00025fa00)
	/home/jmazzite/bin/go-install/go/src/net/http/server.go:2416 +0x1a5
net/http.serverHandler.ServeHTTP(0xc0001802a0, 0x16cd1e0, 0xc000180a80, 0xc00025fa00)
	/home/jmazzite/bin/go-install/go/src/net/http/server.go:2836 +0xa3
net/http.(*conn).serve(0xc00033afa0, 0x16d07a0, 0xc0002f3a40)
	/home/jmazzite/bin/go-install/go/src/net/http/server.go:1924 +0x86c
created by net/http.(*Server).Serve
	/home/jmazzite/bin/go-install/go/src/net/http/server.go:2962 +0x35c
```

**Comment by jmazzitelli** [comment]
Easy to replicate - I found this in the molecule test, but if you just run this, you'll get the panic:

```
curl http://localhost:20001/kiali/api/authenticate
```

You need OpenID installed and configured. My test is on minikube on my local box, with a port-forward to Kiali - to get this environment setup, just install minikube via `hack/k8s-minikube.sh start --dex-enabled true -kv 1.18.0` and then `hack/k8s-minikube port-forward`)

**Comment by jmazzitelli** [comment]
This is what it should be (after applying the PR, I now see this - and this should now pass that particular molecule test task - this is therefore what the openid molecule test failure has been the past week or so - we ignored the test failure so that was our own fault):

```
$ curl http://localhost:20001/kiali/api/authenticate  --dump-header -
HTTP/1.1 400 Bad Request
Content-Type: application/json
Set-Cookie: kiali-token-openid-nonce=; Path=/kiali; Expires=Thu, 01 Jan 1970 00:00:00 GMT; HttpOnly; SameSite=Strict
Vary: Accept-Encoding
Date: Thu, 24 Sep 2020 12:10:09 GMT
Content-Length: 58

{"error":"No nonce code present. Login window timed out."}
```
