### ISSUE TITLE
REST API panic if no Prometheus

### ISSUE THREAD

**Issue by esnible** [kiali/kiali#4014]
**Describe the bug**

Panic via REST API if there is no Prometheus.

To reproduce, I installed a dev version of Istio 1.10, but I did not install Prometheus.

```bash
kubectl -n istio-system exec deployment/kiali -- curl "http://localhost:20001/kiali/api/namespaces/graph?namespaces=default"
```

The response was
```json
{"error":"Post \"http://prometheus.istio-system:9090/api/v1/query\": dial tcp: lookup prometheus.istio-system on 172.21.0.10:53: no such host","detail":"goroutine 186 [running]:\nruntime/debug.Stack(0xc00084e120, 0x81, 0xc00019c3a8)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9f\ngithub.com/kiali/kiali/handlers.handlePanic(0x1d5b9e0, 0xc0000101c0)\n\t/home/fedora/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/handlers/graph.go:86 +0x185\npanic(0x1841540, 0xc00019c3a8)\n\t/usr/local/go/src/runtime/panic.go:965 +0x1b9\ngithub.com/kiali/kiali/graph.CheckError(...)\n\t/home/fedora/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/graph/util.go:38\ngithub.com/kiali/kiali/graph/telemetry/istio.promQuery(0xc000274500, 0x266, 0x0, 0xed8306034, 0x285e8a0, 0x1d7c648, 0xc000483600, 0x0, 0x0, 0x0)\n\t/home/fedora/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/graph/telemetry/istio/istio.go:663 +0x6ba\ngithub.com/kiali/kiali/graph/telemetry/istio.buildNamespaceTrafficMap(0xc0001c21ab, 0x7, 0xc000308210, 0x1, 0x0, 0x0, 0x0, 0x0, 0xc0004f89c0, 0x8bb2c97000, ...)\n\t/home/fedora/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/graph/telemetry/istio/istio.go:97 +0x31f\ngithub.com/kiali/kiali/graph/telemetry/istio.BuildNamespacesTrafficMap(0xc000308210, 0x1, 0x0, 0x0, 0x0, 0x0, 0xc0004f89c0, 0x8bb2c97000, 0x1af5daf, 0x8, ...)\n\t/home/fedora/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/graph/telemetry/istio/istio.go:50 +0x428\ngithub.com/kiali/kiali/graph/api.graphNamespacesIstio(0xc00000a3c0, 0xc0001ad700, 0x1af6a6c, 0x9, 0x1af1831, 0x5, 0x1af0c6b, 0x4, 0x8bb2c97000, 0x1af5daf, ...)\n\t/home/fedora/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/graph/api/api.go:44 +0xb8\ngithub.com/kiali/kiali/graph/api.GraphNamespaces(0xc00000a3c0, 0x1af6a6c, 0x9, 0x1af1831, 0x5, 0x1af0c6b, 0x4, 0x8bb2c97000, 0x1af5daf, 0x8, ...)\n\t/home/fedora/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/graph/api/api.go:26 +0x178\ngithub.com/kiali/kiali/handlers.GraphNamespaces(0x1d5b9e0, 0xc0000101c0, 0xc00083cb00)\n\t/home/fedora/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/handlers/graph.go:51 +0x13c\nnet/http.HandlerFunc.ServeHTTP(0x1bc10a0, 0x1d5b9e0, 0xc0000101c0, 0xc00083cb00)\n\t/usr/local/go/src/net/http/server.go:2069 +0x44\ngithub.com/kiali/kiali/routing.metricHandler.func1(0x1d5b9e0, 0xc0000101c0, 0xc00083cb00)\n\t/home/fedora/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/routing/router.go:92 +0xa3\nnet/http.HandlerFunc.ServeHTTP(0xc0001a94a0, 0x1d5b9e0, 0xc0000101c0, 0xc00083cb00)\n\t/usr/local/go/src/net/http/server.go:2069 +0x44\ngithub.com/kiali/kiali/handlers.AuthenticationHandler.Handle.func1(0x1d5b9e0, 0xc0000101c0, 0xc00083ca00)\n\t/home/fedora/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/handlers/authentication.go:649 +0x1f7\nnet/http.HandlerFunc.ServeHTTP(0xc0006813e0, 0x1d5b9e0, 0xc0000101c0, 0xc00083ca00)\n\t/usr/local/go/src/net/http/server.go:2069 +0x44\ngithub.com/kiali/kiali/server.plainHttpMiddleware.func1(0x1d5b9e0, 0xc0000101c0, 0xc00083ca00)\n\t/home/fedora/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/server/server.go:127 +0x6c\nnet/http.HandlerFunc.ServeHTTP(0xc00019c048, 0x1d5b9e0, 0xc0000101c0, 0xc00083ca00)\n\t/usr/local/go/src/net/http/server.go:2069 +0x44\ngithub.com/gorilla/mux.(*Router).ServeHTTP(0xc000364300, 0x1d5b9e0, 0xc0000101c0, 0xc00083c800)\n\t/home/fedora/workspace/kiali-workflow/kiali-release/pkg/mod/github.com/gorilla/mux@v1.7.4/mux.go:210 +0xd3\ngithub.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1(0x1d5b9e0, 0xc0000101c0, 0xc00083c800)\n\t/home/fedora/workspace/kiali-workflow/kiali-release/pkg/mod/github.com/!n!y!times/gziphandler@v1.1.1/gzip.go:342 +0x302\nnet/http.HandlerFunc.ServeHTTP(0xc00003b260, 0x1d5b9e0, 0xc0000101c0, 0xc00083c800)\n\t/usr/local/go/src/net/http/server.go:2069 +0x44\nnet/http.(*ServeMux).ServeHTTP(0xc00004d580, 0x1d5b9e0, 0xc0000101c0, 0xc00083c800)\n\t/usr/local/go/src/net/http/server.go:2448 +0x1ad\nnet/http.serverHandler.ServeHTTP(0xc0001600e0, 0x1d5b9e0, 0xc0000101c0, 0xc00083c800)\n\t/usr/local/go/src/net/http/server.go:2887 +0xa3\nnet/http.(*conn).serve(0xc000441400, 0x1d5f6b8, 0xc0001495c0)\n\t/usr/local/go/src/net/http/server.go:1952 +0x8cd\ncreated by net/http.(*Server).Serve\n\t/usr/local/go/src/net/http/server.go:3013 +0x39b\n"}%                                                
```

**Versions used**

Kubernetes 1.19, Istio 1.10.
Kiali quay.io/kiali/kiali:v1.34 installed using 

I installed Kiali using

```
kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.10/samples/addons/kiali.yaml
# See https://github.com/istio/istio/issues/27417#issuecomment-729153529 for rationale.
kubectl -n istio-system wait --for=condition=established --timeout=60s crd/monitoringdashboards.monitoring.kiali.io
kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.10/samples/addons/kiali.yaml
kubectl -n istio-system wait --for=condition=available --timeout=600s deployment/kiali
```

**To Reproduce**

`kubectl -n istio-system exec deployment/ -- curl "http://localhost:20001/kiali/api/namespaces/graph?namespaces=default"`

**Expected behavior**

HTTP 503 error (or success with no graph, no namespaces).

See https://github.com/kiali/kiali/blob/master/graph/telemetry/istio/istio.go#L663

**Comment by lucasponce** [comment]
Perhaps the issue here is to improve the error log/msg I guess, the API response sounds expected to me, but probably the log may the user think that something else is happening ?

**Comment by esnible** [comment]
500 errors make me nervous, because there is no way to tell if the programmer intended them or if a bug has been revealed.  If I see a 503 I know the programmer expected the error.

Many orgs have a security policy that bans stack traces in REST output, because it is believed that this reveals information about the code version and internal state of the system that can be used by hackers.  I enjoy seeing the stack trace, it made it easy to find out what was wrong, but when I see one I have no way to know if the programmer intended the stack trace to be visible or not.

When I see a panic I am uncertain if the Kiali server was briefly unavailable or not.  I poked around with _curl_ to make sure there was no denial-of-service attack possibility.  If the `detail` part of the message didn't have panic I would not have taken the time to investigate.

**Comment by lucasponce** [comment]
+1

I guess these error codes can be tweaked, no doubt.
It makes sense.

**Comment by jshaughn** [comment]
@esnible @lucasponce I have created a PR for this issue such that the graph code will now return a 503, and no stack trace, on errors calling the Prom API.  In short, it will assume Prom is unavailable on an API failure.   Note that the Kiali Metrics API still reports a 500 but it does not send a stack trace to the client.
