### ISSUE TITLE
v1.44.0 panic when caches are enabled

### ISSUE THREAD

**Issue by js-timbirkett** [kiali/kiali#4603]
When caching is enabled (default is `true`): 
```
 kubernetes_config:
   cache_enabled: true
```

Kiali throws a lovely big error / panic and proceeds to crashloop:

```
│ panic: interface conversion: interface {} is nil, not string                                                                         │
│ goroutine 430 [running]:                                                                                                             │
│ github.com/kiali/kiali/kubernetes.ParseRegistryConfig(0xc00078a3f0, 0x1faaffe, 0xe, 0xc00078a3f0)                                    │
│     /home/fedora/workspace/kiali-upstream/kiali-release/src/github.com/kiali/kiali/kubernetes/istio.go:242 +0x21b1                   │
│ github.com/kiali/kiali/kubernetes.(*K8SClient).GetRegistryConfiguration(0xc0004401e0, 0x0, 0xc000149b40, 0xc000362540)               │
│     /home/fedora/workspace/kiali-upstream/kiali-release/src/github.com/kiali/kiali/kubernetes/istio.go:175 +0x145                    │
│ github.com/kiali/kiali/business.(*RegistryStatusService).refreshRegistryStatus.func1(0xc000ec2010, 0xc001084ef0, 0xc000ea8018, 0xc00 │
│     /home/fedora/workspace/kiali-upstream/kiali-release/src/github.com/kiali/kiali/business/registry_status.go:225 +0x62             │
│ created by github.com/kiali/kiali/business.(*RegistryStatusService).refreshRegistryStatus                                            │
│     /home/fedora/workspace/kiali-upstream/kiali-release/src/github.com/kiali/kiali/business/registry_status.go:223 +0x13e
```

Istio version: 1.6.14
K8S  version: 1.20.x (AWS EKS)

**Comment by lucasponce** [comment]
> Istio version: 1.6.14

Note that Kiali 1.44 is expected to work with Istio +1.12, so that error is somehow expected.

Take a look to the compatibility matrix:
https://kiali.io/docs/installation/installation-guide/prerequisites/

**Comment by jmazzitelli** [comment]
> Istio version: 1.6.14

Yes, Kiali 1.44 is not compatible with Istio 1.6 - in fact, Istio 1.6 is EOL/out of support even upstream AFAIK.

**Comment by jmazzitelli** [comment]
Yeah, as of Nov 2020 - Istio 1.6 is EOL -- https://istio.io/latest/news/support/announcing-1.6-eol-final/

**Comment by lucasponce** [comment]
Closing as the Istio / Kiali matrix version is not correct.
