### ISSUE TITLE
E2E tests not working with python 3.10

### ISSUE THREAD

**Issue by FilipB** [kiali/kiali#4727]
When running E2E tests with python 3.10 it fails with following error:
```
py.test tests/test_api_methods.py tests/test_kiali_application_endpoint.py tests/test_kiali_bookinfo_namespace_endpoint.py tests/test_kiali_configmap.py tests/test_kiali_external_host_node.py tests/test_kiali_graph_badges.py tests/test_kiali_graph.py tests/test_kiali_health.py tests/test_kiali_istio_clusterrole_binding.py tests/test_kiali_istio_endpoint.py tests/test_kiali_logs.py tests/test_kiali_metrics.py tests/test_kiali_node_detail_graph.py tests/test_kiali_reduced_permissions.py tests/test_kiali_service_endpoint.py tests/test_kiali_traces.py tests/test_kiali_urls.py tests/test_kiali_workload_endpoint.py --disable-warnings --color=yes --junitxml=junit-rest-report.xml
Traceback (most recent call last):
  File "/home/fedora/.local/lib/python3.10/site-packages/_pytest/config.py", line 339, in _getconftestmodules
    return self._path2confmods[path]
KeyError: local('/home/fedora/workspace/kiali/test-jobs/kiali-E2E-tests/kiali/tests/e2e/tests/test_api_methods.py')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/fedora/.local/lib/python3.10/site-packages/_pytest/config.py", line 339, in _getconftestmodules
    return self._path2confmods[path]
KeyError: local('/home/fedora/workspace/kiali/test-jobs/kiali-E2E-tests/kiali/tests/e2e/tests')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/fedora/.local/lib/python3.10/site-packages/_pytest/config.py", line 370, in _importconftest
    return self._conftestpath2mod[conftestpath]
KeyError: local('/home/fedora/workspace/kiali/test-jobs/kiali-E2E-tests/kiali/tests/e2e/tests/conftest.py')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 939, in _find_spec
AttributeError: 'AssertionRewritingHook' object has no attribute 'find_spec'

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/fedora/.local/lib/python3.10/site-packages/_pytest/config.py", line 376, in _importconftest
    mod = conftestpath.pyimport()
  File "/home/fedora/.local/lib/python3.10/site-packages/py/_path/local.py", line 704, in pyimport
    __import__(modname)
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 941, in _find_spec
  File "<frozen importlib._bootstrap>", line 915, in _find_spec_legacy
  File "/home/fedora/.local/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 140, in find_module
    source_stat, co = _rewrite_test(self.config, fn_pypath)
  File "/home/fedora/.local/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 333, in _rewrite_test
    co = compile(tree, fn.strpath, "exec", dont_inherit=True)
TypeError: required field "lineno" missing from alias
ERROR: could not load /home/fedora/workspace/kiali/test-jobs/kiali-E2E-tests/kiali/tests/e2e/tests/conftest.py

```

**Comment by FilipB** [comment]
@mattmahoneyrh cc

**Comment by mattmahoneyrh** [comment]
@FilipB What is the need for upgrading to phton 3.10, is this a short term or future?

**Comment by FilipB** [comment]
@mattmahoneyrh python 3.10 is a default version on Fedora 35. Our jenkins agents are based on Fedora so as soon as we update our jenkins agents to the latest Fedora, we will hit this issue.
