### ISSUE TITLE
htmlproofer update in kiali.io 

### ISSUE THREAD

**Issue by josunect** [kiali/kiali#5313]
htmlproofer has been updated to V. 4.2.0 (It was v. htmlproofer 3.19.3 in my local environment) and the parameters have been changed, causing an OptionParser error: 

```
Total in 1651 ms
htmlproofer 4.2.0 | Error:  Whoops, we can't understand your command.
htmlproofer 4.2.0 | Error:  invalid option: --empty_alt_ignore
htmlproofer 4.2.0 | Error:  Run your command again with the --help switch to see available options.
Traceback (most recent call last):
	4: from /usr/local/bin/htmlproofer:23:in `<main>'
	3: from /usr/local/bin/htmlproofer:23:in `load'
	2: from /usr/local/share/gems/gems/html-proofer-4.2.0/bin/htmlproofer:11:in `<top (required)>'
	1: from /usr/local/share/gems/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
/usr/local/share/gems/gems/mercenary-0.4.0/lib/mercenary/program.rb:33:in `go': invalid option: --empty_alt_ignore (OptionParser::InvalidOption)
make: *** [Makefile:74: validate-site] Error 1
```
I've found this error in https://github.com/kiali/kiali.io/pull/537
I was able to reproduce it locally without the use of the cache (--no-cache) and force the image generation: 

make -e FORCE_BUILD=true validate-site

It looks like the parameters have been changed, and might be also have change the validation rules. 

- https://github.com/gjtorikian/html-proofer
- https://github.com/gjtorikian/html-proofer/blob/main/CHANGELOG.md

Remove html-proofer version from Dockerfile (Revert https://github.com/kiali/kiali.io/pull/559)

**Comment by josunect** [comment]
I can be working on this

**Comment by josunect** [comment]
Removing the "waiting external" tag, HTMLProofer 4.3 was released.
