### ISSUE TITLE
 Kiali errors out loading workload graph in 'default' namespace 

### ISSUE THREAD

**Issue by Anand25021998** [kiali/kiali#5696]
It’s able to load the workload graph for couple of deployments I checked in different namespaces but errors out while loading workload graph of any workload in the 'default' namespace. The only difference is that I don't have istio injected on a namespace level in the 'default' namespace and it's on workload level but to my understanding it shouldn't matter to Kiali. It's able to load all the app graphs in the 'default' namespace and the issue is seen only with workload graphs. I can’t derive much from the stack trace in pod logs which are:

```
2023-01-06T08:54:20Z ERR Failed ID gen2: cluster=[Kubernetes] namespace=[default] workload=[unknown] app=[test-app] version=[29917846] service=[] graphType=[workload]: goroutine 2741890 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.17.10/x64/src/runtime/debug/stack.go:24 +0x65
github.com/kiali/kiali/handlers.handlePanic({0x2097ea0, 0xc004ee8690})
        /home/runner/work/kiali/kiali/handlers/graph.go:86 +0x219
panic({0x1a243e0, 0xc0040fddf0})
        /opt/hostedtoolcache/go/1.17.10/x64/src/runtime/panic.go:1038 +0x215
github.com/kiali/kiali/graph.Id({0xc006fddb10, 0xc003cdb2d8}, {0xc006fddb40, 0x7f60a06cf538}, {0x0, 0x0}, {0xc006fddb40, 0x23}, {0xc006fddb07, 0x7}, ...)
        /home/runner/work/kiali/kiali/graph/types.go:213 +0xde9
github.com/kiali/kiali/graph/telemetry/istio/appender.ResponseTimeAppender.addResponseTime({{0xc00274f559, 0x8}, 0x1, 0xc00530f4d0, 0x3fee666666666666, 0x63b7e1bc, {{0x1dd45a2, 0x8}, {0x1dd45a2, 0x8}, ...}}, ...)
        /home/runner/work/kiali/kiali/graph/telemetry/istio/appender/response_time.go:229 +0xe5
github.com/kiali/kiali/graph/telemetry/istio/appender.ResponseTimeAppender.populateResponseTimeMap({{0xc00274f559, 0x8}, 0x1, 0xc00530f4d0, 0x3fee666666666666, 0x63b7e1bc, {{0x1dd45a2, 0x8}, {0x1dd45a2, 0x8}, ...}}, ...)
        /home/runner/work/kiali/kiali/graph/telemetry/istio/appender/response_time.go:223 +0xc25
github.com/kiali/kiali/graph/telemetry/istio/appender.ResponseTimeAppender.appendGraph({{0xc00274f559, 0x8}, 0x1, 0xc00530f4d0, 0x3fee666666666666, 0x63b7e1bc, {{0x1dd45a2, 0x8}, {0x1dd45a2, 0x8}, ...}}, ...)
        /home/runner/work/kiali/kiali/graph/telemetry/istio/appender/response_time.go:134 +0xca8
github.com/kiali/kiali/graph/telemetry/istio/appender.ResponseTimeAppender.AppendGraph({{0xc00274f559, 0x8}, 0x1, 0xc00530f4d0, 0x3fee666666666666, 0x63b7e1bc, {{0x1dd45a2, 0x8}, {0x1dd45a2, 0x8}, ...}}, ...)
        /home/runner/work/kiali/kiali/graph/telemetry/istio/appender/response_time.go:65 +0x13e
github.com/kiali/kiali/graph/telemetry/istio.BuildNodeTrafficMap({0xc00530f530, {0x0, {0xc004724b40, 0x9, 0x9}}, 0x0, 0x1, 0xc00530f4d0, {{0x1dd45a2, 0x8}, ...}, ...}, ...)
        /home/runner/work/kiali/kiali/graph/telemetry/istio/istio.go:461 +0x472
github.com/kiali/kiali/graph/api.graphNodeIstio({_, _}, _, _, {{0x1dd554a, 0x9}, {0x1dcfda7, 0x5}, {{0x1dcf0af, 0x4}, ...}, ...})
        /home/runner/work/kiali/kiali/graph/api/api.go:90 +0x125
github.com/kiali/kiali/graph/api.GraphNode({_, _}, _, {{0x1dd554a, 0x9}, {0x1dcfda7, 0x5}, {{0x1dcf0af, 0x4}, {0x34630b8a000, ...}}, ...})
        /home/runner/work/kiali/kiali/graph/api/api.go:72 +0x1d5
github.com/kiali/kiali/handlers.GraphNode({0x2097ea0, 0xc004ee8690}, 0xc0007e2300)
        /home/runner/work/kiali/kiali/handlers/graph.go:64 +0x165
net/http.HandlerFunc.ServeHTTP(0x1dda35c, {0x2097ea0, 0xc004ee8690}, 0x7f60a06c5f18)
        /opt/hostedtoolcache/go/1.17.10/x64/src/net/http/server.go:2047 +0x2f
github.com/kiali/kiali/routing.metricHandler.func1({0x20a5640, 0xc005c44070}, 0x2063001)
        /home/runner/work/kiali/kiali/routing/router.go:145 +0x144
net/http.HandlerFunc.ServeHTTP(0x20ada78, {0x20a5640, 0xc005c44070}, 0x20630e0)
        /opt/hostedtoolcache/go/1.17.10/x64/src/net/http/server.go:2047 +0x2f
github.com/kiali/kiali/handlers.AuthenticationHandler.Handle.func1({0x20a5640, 0xc005c44070}, 0xc0007e2100)
        /home/runner/work/kiali/kiali/handlers/authentication.go:79 +0x514
net/http.HandlerFunc.ServeHTTP(0x1a1e620, {0x20a5640, 0xc005c44070}, 0xc000226640)
        /opt/hostedtoolcache/go/1.17.10/x64/src/net/http/server.go:2047 +0x2f
github.com/kiali/kiali/server.plainHttpMiddleware.func1({0x20a5640, 0xc005c44070}, 0xc00530f2c0)
        /home/runner/work/kiali/kiali/server/server.go:152 +0x65
net/http.HandlerFunc.ServeHTTP(0xc0007e2000, {0x20a5640, 0xc005c44070}, 0xc)
        /opt/hostedtoolcache/go/1.17.10/x64/src/net/http/server.go:2047 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000058240, {0x20a5640, 0xc005c44070}, 0xc006caec00)
        /home/runner/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
github.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1({0x20a54f0, 0xc00627c1c0}, 0xe6165688818c94)
        /home/runner/go/pkg/mod/github.com/!n!y!times/gziphandler@v1.1.1/gzip.go:336 +0x23c
net/http.HandlerFunc.ServeHTTP(0x0, {0x20a54f0, 0xc00627c1c0}, 0x0)
        /opt/hostedtoolcache/go/1.17.10/x64/src/net/http/server.go:2047 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc00274f540, {0x20a54f0, 0xc00627c1c0}, 0xc006caec00)
        /opt/hostedtoolcache/go/1.17.10/x64/src/net/http/server.go:2425 +0x149
net/http.serverHandler.ServeHTTP({0xc00748c030}, {0x20a54f0, 0xc00627c1c0}, 0xc006caec00)
        /opt/hostedtoolcache/go/1.17.10/x64/src/net/http/server.go:2879 +0x43b
net/http.(*conn).serve(0xc001930280, {0x20ada78, 0xc003758d80})
        /opt/hostedtoolcache/go/1.17.10/x64/src/net/http/server.go:1930 +0xb08
created by net/http.(*Server).Serve
        /opt/hostedtoolcache/go/1.17.10/x64/src/net/http/server.go:3034 +0x4e8
```

Any pointers on what could be causing this are appreciated.

I am running the latest Kiali v1.58.0

**Comment by jshaughn** [comment]
Which version of Istio?

**Comment by Anand25021998** [comment]
> 

v1.15.3

**Comment by jshaughn** [comment]
Yes, I just wanted to be sure, because the error would indicate something unusual in the Prometheus telemetry.  Does the problem go away if you disable the Response Time edge labeling?

**Comment by Anand25021998** [comment]
The problem persists but I see a different traceback now (I unchecked all the edge labeling to be sure)
```

2023-01-06T16:59:04Z ERR Failed ID gen2: cluster=[Kubernetes] namespace=[default] workload=[unknown] app=[a4trace] version=[29917846] service=[] graphType=[workload]: goroutine 6571107 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.17.10/x64/src/runtime/debug/stack.go:24 +0x65
github.com/kiali/kiali/handlers.handlePanic({0x2097ea0, 0xc004214750})
        /home/runner/work/kiali/kiali/handlers/graph.go:86 +0x219
panic({0x1a243e0, 0xc002f29990})
        /opt/hostedtoolcache/go/1.17.10/x64/src/runtime/panic.go:1038 +0x215
github.com/kiali/kiali/graph.Id({0xc006670ea0, 0x7f60793c52f8}, {0xc006670ed0, 0x10}, {0x0, 0x0}, {0xc006670ed0, 0xc003624fb8}, {0xc006670e97, 0x7}, ...)
        /home/runner/work/kiali/kiali/graph/types.go:213 +0xde9
github.com/kiali/kiali/graph/telemetry/istio.addNode(_, {_, _}, {_, _}, {_, _}, {_, _}, {0xc006670e97, ...}, ...)
        /home/runner/work/kiali/kiali/graph/telemetry/istio/istio.go:425 +0xfd
github.com/kiali/kiali/graph/telemetry/istio.addTraffic(_, {_, _}, _, _, {_, _}, {_, _}, {0x300f648, ...}, ...)
        /home/runner/work/kiali/kiali/graph/telemetry/istio/istio.go:362 +0x11a
github.com/kiali/kiali/graph/telemetry/istio.populateTrafficMap(_, _, {_, _}, {0xc006920420, {0x0, {0xc0055fe2a0, 0x7, 0x7}}, 0x0, ...})
        /home/runner/work/kiali/kiali/graph/telemetry/istio/istio.go:357 +0x10d1
github.com/kiali/kiali/graph/telemetry/istio.buildNamespaceTrafficMap({_, _}, {_, _}, {0xc006920420, {0x0, {0xc0055fe2a0, 0x7, 0x7}}, 0x0, ...}, ...)
        /home/runner/work/kiali/kiali/graph/telemetry/istio/istio.go:152 +0x8f4
github.com/kiali/kiali/graph/telemetry/istio.BuildNamespacesTrafficMap({_, _}, {0xc006920420, {0x0, {0xc0055fe2a0, 0x7, 0x7}}, 0x0, 0x1, 0xc0022150e0, ...}, ...)
        /home/runner/work/kiali/kiali/graph/telemetry/istio/istio.go:69 +0x445
github.com/kiali/kiali/graph/api.graphNamespacesIstio({_, _}, _, _, {{0x1dd554a, 0x9}, {0x1dcfda7, 0x5}, {{0xc004130a77, 0x11}, ...}, ...})
        /home/runner/work/kiali/kiali/graph/api/api.go:52 +0x126
github.com/kiali/kiali/graph/api.GraphNamespaces({_, _}, _, {{0x1dd554a, 0x9}, {0x1dcfda7, 0x5}, {{0xc004130a77, 0x11}, {0x34630b8a000, ...}}, ...})
        /home/runner/work/kiali/kiali/graph/api/api.go:33 +0x2fb
github.com/kiali/kiali/handlers.GraphNamespaces({0x2097ea0, 0xc004214750}, 0xc002bb5800)
        /home/runner/work/kiali/kiali/handlers/graph.go:51 +0x165
net/http.HandlerFunc.ServeHTTP(0x1ddd094, {0x2097ea0, 0xc004214750}, 0x7f60a06d8108)
        /opt/hostedtoolcache/go/1.17.10/x64/src/net/http/server.go:2047 +0x2f
github.com/kiali/kiali/routing.metricHandler.func1({0x20a5640, 0xc0055fe230}, 0x2063001)
        /home/runner/work/kiali/kiali/routing/router.go:145 +0x144
net/http.HandlerFunc.ServeHTTP(0x20ada78, {0x20a5640, 0xc0055fe230}, 0x20630e0)
        /opt/hostedtoolcache/go/1.17.10/x64/src/net/http/server.go:2047 +0x2f
github.com/kiali/kiali/handlers.AuthenticationHandler.Handle.func1({0x20a5640, 0xc0055fe230}, 0xc002bb5600)
        /home/runner/work/kiali/kiali/handlers/authentication.go:79 +0x514
net/http.HandlerFunc.ServeHTTP(0x1a1e620, {0x20a5640, 0xc0055fe230}, 0xc000116960)
        /opt/hostedtoolcache/go/1.17.10/x64/src/net/http/server.go:2047 +0x2f
github.com/kiali/kiali/server.plainHttpMiddleware.func1({0x20a5640, 0xc0055fe230}, 0xc002214ff0)
        /home/runner/work/kiali/kiali/server/server.go:152 +0x65
net/http.HandlerFunc.ServeHTTP(0xc002bb5500, {0x20a5640, 0xc0055fe230}, 0xc)
        /opt/hostedtoolcache/go/1.17.10/x64/src/net/http/server.go:2047 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000058240, {0x20a5640, 0xc0055fe230}, 0xc002bb5400)
        /home/runner/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
github.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1({0x20a54f0, 0xc0039a8d20}, 0xe632bcaeec0802)
        /home/runner/go/pkg/mod/github.com/!n!y!times/gziphandler@v1.1.1/gzip.go:336 +0x23c
net/http.HandlerFunc.ServeHTTP(0x4, {0x20a54f0, 0xc0039a8d20}, 0x7f60a06d8108)
        /opt/hostedtoolcache/go/1.17.10/x64/src/net/http/server.go:2047 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc004130a20, {0x20a54f0, 0xc0039a8d20}, 0xc002bb5400)
        /opt/hostedtoolcache/go/1.17.10/x64/src/net/http/server.go:2425 +0x149
net/http.serverHandler.ServeHTTP({0xc00402d2c0}, {0x20a54f0, 0xc0039a8d20}, 0xc002bb5400)
        /opt/hostedtoolcache/go/1.17.10/x64/src/net/http/server.go:2879 +0x43b
net/http.(*conn).serve(0xc005820280, {0x20ada78, 0xc003758d80})
        /opt/hostedtoolcache/go/1.17.10/x64/src/net/http/server.go:1930 +0xb08
created by net/http.(*Server).Serve
        /opt/hostedtoolcache/go/1.17.10/x64/src/net/http/server.go:3034 +0x4e8
```

**Comment by Anand25021998** [comment]
> Can you think of any reason why this `a4trace` app may behave this way? Do you actually have a workload named 'unknown'?

I am seeing  workload=[unknown] for any app in this entire namespace (and this namespace only, things work fine with other namespaces). And, no, I don't have a workload named 'unknown'. But let me look more into the prometheus metrics to see if I can find something.



> Or perhaps deleting your Prom db and starting over with a new one.

to give some context, I am deploying/exploring Istio + Kiali at my current workplace, so deleting the Prom db is just not an option :)
Thanks for explaining this issue btw. I will get back if I find something useful.

**Comment by jshaughn** [comment]
You said before that `Default` is outside the mesh, The deployments here are not injected with sidecars, right?  Are these workloads the source of requests, or the destinations, or both?

**Comment by Anand25021998** [comment]
So I haven't enabled istio injection for the entire `Default` namespace but I have enabled injection for couple of deployments in that namespace (using the relevant deployment annotations). I am trying to get the workload graph for one of the two deployment but there are additional deployments (with no istio sidecar injected) which are coming into picture as "destination" deployment. All our deployments (irrespective of injection) have `app` and `app.kubernetes.io/name ` labels set.

**Comment by jshaughn** [comment]
I've created a PR to hopefully avoid this panic scenario, because there really isn't much anyone can do with a panic.  Instead the idea is to inject an "unknown" service into the graph.  Because you are the first person encountering this scenario, you'll be the best to evaluate if it's a reasonable approach, and works reasonably well.  With luck this PR may make it into Monday's release of v1.62.

**Comment by Anand25021998** [comment]
Thanks a ton for the quick fix. Looking forward to trying it with whichever release has it.

**Comment by Anand25021998** [comment]
So, I upgraded to istio v1.16.1 and kiali 1.61.0 and I don't see any errors anymore (note that I first upgraded to v1.62.0 to test the fix but ran into a wider issue with graphs on v1.62.0 - I have opened a separate issue for that).

**Comment by jshaughn** [comment]
So I guess this is good news, as you have a combination that is working well for you.  I wonder whether the problematic telemetry simply went away, because if it were still present in your requested time window, I would expect you'd see the same behavior.

As for your v1.62 issue, that's obvioulys not good.  I'll continue over in that issue...

**Comment by jshaughn** [comment]
@RaiAnandKr, it seems you may be busy, and so I'll just try an be pro-active here.    I created https://github.com/kiali/kiali/issues/5890 as a follow-up to this issue.  The work for that will be another round of improvement to avoid a panic given unexpected telemetry.

Still, please let me know if in fact you are seeing a panic with your latest canary scenario.
