### ISSUE TITLE
segfault in dashboards_test

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#6354]
I didn't want to lose this, so I'm quickly creating an issue. Looks like a segfault in a test. I saw this in a [PR](https://github.com/kiali/kiali/pull/6352) that had nothing to do with this (it was just updating the bookinfo install hack script).

_UPDATE_ ooo.. but this segfault is accessing a bookinfo app - so... maybe it is related. If I find that this is due to a problem in my PR, I'll close this issue_

```
=== RUN   TestAppDashboard
    dashboards_test.go:32: 
        	Error Trace:	/home/runner/work/kiali/kiali/tests/integration/tests/dashboards_test.go:32
        	            				/home/runner/work/kiali/kiali/tests/integration/tests/dashboards_test.go:14
        	Error:      	Expected nil, but got: &url.Error{Op:"Get", URL:"http://172.18.255.71:20001/kiali/api/namespaces/bookinfo/apps/details/dashboard", Err:(*http.httpError)(0xc0003e06c0)}
        	Test:       	TestAppDashboard
    dashboards_test.go:33: 
        	Error Trace:	/home/runner/work/kiali/kiali/tests/integration/tests/dashboards_test.go:33
        	            				/home/runner/work/kiali/kiali/tests/integration/tests/dashboards_test.go:14
        	Error:      	Expected value not to be nil.
        	Test:       	TestAppDashboard
--- FAIL: TestAppDashboard (10.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x185bd4a]

goroutine 105 [running]:
testing.tRunner.func1.2({0x1a80be0, 0x2db2610})
	/opt/hostedtoolcache/go/1.20.5/x64/src/testing/testing.go:1526 +0x24e
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.20.5/x64/src/testing/testing.go:1529 +0x39f
panic({0x1a80be0, 0x2db2610})
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/panic.go:884 +0x213
github.com/kiali/kiali/tests/integration/tests.assertDashboards({0x1d1505c?, 0x2d4d120?}, {0x1d1a182?, 0x52b365?}, {0x1d18a23?, 0x0?}, 0x0?)
	/home/runner/work/kiali/kiali/tests/integration/tests/dashboards_test.go:34 +0x8a
github.com/kiali/kiali/tests/integration/tests.TestAppDashboard(0xc0005be360?)
	/home/runner/work/kiali/kiali/tests/integration/tests/dashboards_test.go:14 +0x5a
testing.tRunner(0xc0001049c0, 0x1e21ab0)
	/opt/hostedtoolcache/go/1.20.5/x64/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.20.5/x64/src/testing/testing.go:1629 +0x3ea
exit status 2
FAIL	github.com/kiali/kiali/tests/integration/tests	[45](https://github.com/kiali/kiali/actions/runs/5555461159/jobs/10146870179?pr=6352#step:10:46).3[64](https://github.com/kiali/kiali/actions/runs/5555461159/jobs/10146870179?pr=6352#step:10:65)s
Error: Process completed with exit code 1.
```

**Comment by jmazzitelli** [comment]
That test passed when I ran it a second time... looks like a flaky test, probably due to the demos not installing properly. I think this is nothing to worry about.
