### ISSUE TITLE
"Cannot load the graph: json: cannot unmarshal object into Go value of type []*kubernetes.RegistryEndpoint"

### ISSUE THREAD

**Issue by howardjohn** [kiali/kiali#6510]
UI fails to load with this error: `Cannot load the graph: json: cannot unmarshal object into Go value of type []*kubernetes.RegistryEndpoint`

Image `quay.io/kiali/kiali:v1.72`

Cluster is GKE 1.27

Running OSS Istio from master with ambient enabled

```
2023-08-22T23:34:46Z ERR json: cannot unmarshal object into Go value of type []*kubernetes.RegistryEndpoint: goroutine 6341 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.20.5/x64/src/runtime/debug/stack.go:24 +0x65
github.com/kiali/kiali/handlers.handlePanic({0x232aee0, 0xc000cb3b90})
        /home/runner/work/kiali/kiali/handlers/graph.go:86 +0x219
panic({0x1c286e0, 0xc0003ad8f0})
        /opt/hostedtoolcache/go/1.20.5/x64/src/runtime/panic.go:884 +0x213
github.com/kiali/kiali/graph.CheckError(...)
        /home/runner/work/kiali/kiali/graph/util.go:38
github.com/kiali/kiali/graph/telemetry/istio/appender.getServiceList({0xc000f35986, 0xa}, {0xc000540c10, 0x6}, 0xc00154bda0)
        /home/runner/work/kiali/kiali/graph/telemetry/istio/appender/appender.go:291 +0x314
github.com/kiali/kiali/graph/telemetry/istio/appender.getServiceLists(0x8?, {0xc000540c10, 0x6}, 0xc00079d050?)
        /home/runner/work/kiali/kiali/graph/telemetry/istio/appender/appender.go:264 +0xac
github.com/kiali/kiali/graph/telemetry/istio/appender.IstioAppender.AppendGraph({0x202afe8?}, 0xc00154be00, 0xc00059c240?, 0xc000c85908)
        /home/runner/work/kiali/kiali/graph/telemetry/istio/appender/istio_details.go:47 +0x65
github.com/kiali/kiali/graph/telemetry/istio.BuildNamespacesTrafficMap({_, _}, {0xc00154bc50, {0x0, {0xc00150b440, 0x6, 0x6}}, 0x0, 0x1, 0xc00154bb90, ...}, ...)
        /home/runner/work/kiali/kiali/graph/telemetry/istio/istio.go:80 +0x6a3
github.com/kiali/kiali/graph/api.graphNamespacesIstio({_, _}, _, _, {{0x203097d, 0x9}, {0x202afe8, 0x5}, {{0xc000540b79, 0x15}, ...}, ...})
        /home/runner/work/kiali/kiali/graph/api/api.go:52 +0x126
github.com/kiali/kiali/graph/api.GraphNamespaces({_, _}, _, {{0x203097d, 0x9}, {0x202afe8, 0x5}, {{0xc000540b79, 0x15}, {0xdf8475800, ...}}, ...})
        /home/runner/work/kiali/kiali/graph/api/api.go:33 +0x2fb
github.com/kiali/kiali/handlers.GraphNamespaces({0x232aee0, 0xc000cb3b90}, 0xc000f25400)
        /home/runner/work/kiali/kiali/handlers/graph.go:51 +0x165
net/http.HandlerFunc.ServeHTTP(0x2038cfd?, {0x232aee0?, 0xc000cb3b90?}, 0x7aa179d53840?)
        /opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2122 +0x2f
github.com/kiali/kiali/routing.metricHandler.func1({0x2339a90?, 0xc00044c930}, 0xc00082b901?)
        /home/runner/work/kiali/kiali/routing/router.go:145 +0x13b
net/http.HandlerFunc.ServeHTTP(0x233aec8?, {0x2339a90?, 0xc00044c930?}, 0xc00082b910?)
        /opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2122 +0x2f
github.com/kiali/kiali/handlers.AuthenticationHandler.Handle.func1({0x2339a90, 0xc00044c930}, 0xc000f25200)
        /home/runner/work/kiali/kiali/handlers/authentication.go:79 +0x3fd
net/http.HandlerFunc.ServeHTTP(0x233aec8?, {0x2339a90?, 0xc00044c930?}, 0x230f150?)
        /opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2122 +0x2f
github.com/kiali/kiali/server.plainHttpMiddleware.func1({0x2339a90?, 0xc00044c930?}, 0xc00154ba70?)
        /home/runner/work/kiali/kiali/server/server.go:157 +0x65
net/http.HandlerFunc.ServeHTTP(0xc000f25100?, {0x2339a90?, 0xc00044c930?}, 0x2?)
        /opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2122 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000000f00, {0x2339a90, 0xc00044c930}, 0xc0001b4400)
        /home/runner/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
github.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1({0x2339940, 0xc000ee01c0}, 0x0?)
        /home/runner/go/pkg/mod/github.com/!n!y!times/gziphandler@v1.1.1/gzip.go:336 +0x24e
net/http.HandlerFunc.ServeHTTP(0xc0005e8700?, {0x2339940?, 0xc000ee01c0?}, 0x40d92a?)
        /opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2122 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc000540b20?, {0x2339940, 0xc000ee01c0}, 0xc0001b4400)
        /opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2500 +0x149
net/http.serverHandler.ServeHTTP({0xc000d99620?}, {0x2339940, 0xc000ee01c0}, 0xc0001b4400)
        /opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2936 +0x316
net/http.(*conn).serve(0xc000b36a20, {0x233aec8, 0xc000cb1ad0})
        /opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:1995 +0x612
created by net/http.(*Server).Serve
        /opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:3089 +0x5ed
```

**Comment by howardjohn** [comment]
Ha funny I found this, since I think I also broke it! https://github.com/istio/istio/pull/46329

Looks like we depended on the internal implementation details of /debug/endpointz which isn't a stable interface

**Comment by lucamaf** [comment]
same happening for me with maistra v 3.0 and openshift 4.13

**Comment by howardjohn** [comment]
it should be 1.20+ impacted only afaik

**Comment by jmazzitelli** [comment]
Ah. ok.. I see you are saying this was in master.. I was thinking that's 1.19 but its for 1.20 now.

That will give us some time to figure out what to do.

**Comment by jmazzitelli** [comment]
We are going to need to tweek this to take into account the changes:

https://github.com/kiali/kiali/blob/v1.72.0/kubernetes/types.go#L283-L287

**Comment by jshaughn** [comment]
Can we make the change and not break 1.19 and earlier?

**Comment by jmazzitelli** [comment]
Some reported this same issue in Istio 1.19 - see https://github.com/kiali/kiali/issues/6591

**Comment by howardjohn** [comment]
hmm, https://github.com/istio/istio/pull/46329 is definitely not in 1.19.

Its possible the user just was running `:latest` without knowing it?

**Comment by jmazzitelli** [comment]
@snahil was the one that reported this... I assume he really wasn't running 1.19 even though that was the version he reported. @snahil - you might want to confirm the version of Istio you installed when you saw this error.

**Comment by snahil** [comment]
![image](https://github.com/kiali/kiali/assets/16596896/d06b203a-6c02-452c-99a3-6abf74fcea83)

**Comment by snahil** [comment]
![image](https://github.com/kiali/kiali/assets/16596896/a306155e-1c36-4566-9d35-8ed6d8a52ab3)

**Comment by jmazzitelli** [comment]
@snahil But what is the version of the images that are used? What you posted just shows the version of the helm chart used (which may or may not have been configured to load different version of binaries, such as `:latest`).

Run this and see what the container image is for istiod:

`kubectl get pods -n istio-system -l app=istiod -o jsonpath='{.items..spec.containers[*].image}{"\n"}'`

Also, go into the Kiali "About" box and tell us what version of Istio it says it is talking to.. you get the About box from the top-right drop down menu:

![image](https://github.com/kiali/kiali/assets/2029470/80701cab-31e3-4549-b3b5-7d866798f8c2)

**Comment by snahil** [comment]
![image](https://github.com/kiali/kiali/assets/16596896/843b1eed-6112-487a-a048-5d74012f025c)
![image](https://github.com/kiali/kiali/assets/16596896/49ee8788-a173-459b-a009-31816c682404)

**Comment by jmazzitelli** [comment]
@snahil OK, there you go. You say you are using  Istio 1.19, but you are not. You are using a developer's build of 1.20, which goes to what @howardjohn was saying - the issue you are seeing is not found in 1.19, only in the master build (which is currently for 1.20).

![image](https://github.com/kiali/kiali/assets/2029470/6fdbe603-348d-4d1d-bf1a-6e90c4b86bc6)

So, your issue is not an issue today - it will be addressed before 1.20 is released.

**Comment by snahil** [comment]
@jmazzitelli  ok!. But I am using Helm chart version 1.19 looks like it does not have the same istio version, Kindly provide the Helm chart version that can be used as i have tested few of them and they had the same issue.

**Comment by jmazzitelli** [comment]
I never install Istio with helm - I do not know where they are. Where did you get your helm chart?

I install using the istioctl and the istio tarball downloaded from the github release pages.

Install Istio following the instructions here and you should be able to get Istio 1.19 installed properly: https://istio.io/latest/docs/setup/getting-started/

**Comment by jmazzitelli** [comment]
BTW: we have now veered away from the purpose of this issue. This is a question for the Istio team for "How do I install Istio 1.19 via helm"... please go to the general Istio slack channel or other Istio support channels for details on that.

**Comment by snahil** [comment]
Cool!. Looks like that's the issue, the helm chart is not working in my case. 
Ref:- https://istio.io/latest/docs/setup/install/helm/

**Comment by jshaughn** [comment]
Closing as this seems resolved!

**Comment by jmazzitelli** [comment]
Only that off-track issue about the helm chart is resolved, not the original issue which was written up (FWIW, this is why I like to avoid hi-jacking issues with other unrelated issues).

The original issue is still going to be a problem that we need to address before istio 1.20 is released

**Comment by jmazzitelli** [comment]
Just documenting what the latest json looks like (I ran the latest 1.20 dev build and printed out the `/debug/endpointz` results from istiod that Kiali gets back - this was running a simple istio install on KinD): 

[registry.json.txt](https://github.com/kiali/kiali/files/12610748/registry.json.txt)

**Comment by jshaughn** [comment]
It's understood that we depend on an unstable interface, but it should be noted that to do a lot of valuable things from the observability and mgmt side, this interface is very important.  It would be great if there were a stable mgmt interface.

**Comment by jmazzitelli** [comment]
One thing that scares me with this change is the `/debug/endpointz` no longer contain information about the services that it did before -- this is missing now:

https://github.com/kiali/kiali/blob/v1.73.0/kubernetes/types.go#L255

```go
		Service     IstioService `json:"service,omitempty"`
```

That Service data provides things like [protocol](https://github.com/kiali/kiali/blob/v1.73.0/kubernetes/types.go#L317) (among other things) that is not in the JSON that comes back from `/debug/endpointz` but that Kiali code uses (at least, I can see references to this data).

**Comment by jmazzitelli** [comment]
To get a good example of what it now looks like, deploy istio 1.20 and the electronic demo and look at istiod's /debug/endpointz results:

Install Istio 1.20 (only available as a dev build right now):
```
hack/istio/download-istio.sh -div 1.20-dev
hack/istio/install-istio-via-istioctl.sh -ih default -it default
```

Install demo:
```
kubectl create namespace electronic-shop
kubectl label namespace electronic-shop istio-injection=enabled
kubectl apply -n electronic-shop -f <(curl -L https://raw.githubusercontent.com/kiali/demos/master/electronic-shop/electronic-shop.yaml)
```

Get istiod data:
```
kubectl exec -it -n istio-system deploy/istiod -- curl http://localhost:15014/debug/endpointz | jq 
```
