### ISSUE TITLE
Kiali fails on OCP cluster

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#6517]
Nightly Jenkins pipeline is failing to run integration tests.
Kiali pod is crashing.

Errors in Kiali logs:
```
{"level":"info","time":"2023-08-24T09:37:37Z","message":"Adding a RegistryRefreshHandler"}
2023-08-24T09:37:37Z INF Kiali: Version: v1.73.0-SNAPSHOT, Commit: c24629daca76d00fe082127cab0cce5b5bde1dd1, Go: 1.20.5
2023-08-24T09:37:37Z INF Using authentication strategy [openshift]
2023-08-24T09:37:37Z INF Some validation errors will be ignored [KIA1301]. If these errors do occur, they will still be logged. If you think the validation errors you see are incorrect, please report them to the Kiali team if you have not done so already and provide the details of your scenario. This will keep Kiali validations strong for the whole community.
2023-08-24T09:37:38Z INF Initializing Kiali Cache
2023-08-24T09:37:38Z INF Adding a RegistryRefreshHandler
2023-08-24T09:37:38Z INF [Kiali Cache] Kube cache is active for cluster: [cluster-default]
2023-08-24T09:37:38Z INF [Kiali Cache] Waiting for namespace-scoped for namespace: bookinfo cache to sync
2023-08-24T09:37:38Z INF [Kiali Cache] Started
2023-08-24T09:37:38Z INF [Kiali Cache] Waiting for namespace-scoped for namespace: istio-system cache to sync
2023-08-24T09:37:38Z INF [Kiali Cache] Started
2023-08-24T09:37:38Z INF Server endpoint will start at [:20001/]
2023-08-24T09:37:38Z INF Server endpoint will serve static content from [/opt/kiali/console]
2023-08-24T09:37:38Z INF Starting Metrics Server on [:9090]
2023-08-24T09:37:38Z INF Server endpoint will require https
2023-08-24T09:37:38Z INF Server will support protocols: [h2 http/1.1]
2023-08-24T09:46:27Z INF [Prom Cache] Enabled
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x1998732]

goroutine 4587 [running]:
github.com/kiali/kiali/kubernetes/cache.(*kubeCache).GetServices(0x1d52de0?, {0x0, 0x0}, 0x19?)
	/home/fedora/go/src/github.com/kiali/kiali/kubernetes/cache/kube_cache.go:732 +0x132
github.com/kiali/kiali/business.(*MeshService).discoverKiali(0xc000277468, {0x33dc100?, 0xc001762470?}, {0xc000844630, 0xf}, 0xa80?)
	/home/fedora/go/src/github.com/kiali/kiali/business/mesh.go:324 +0xf6
github.com/kiali/kiali/business.(*MeshService).GetClusters(0xc000277468, 0xc000058068?)
	/home/fedora/go/src/github.com/kiali/kiali/business/mesh.go:285 +0x22e
github.com/kiali/kiali/business.(*MeshService).GetMesh(0xc000277468, {0x23a19c8, 0xc000058068})
	/home/fedora/go/src/github.com/kiali/kiali/business/mesh.go:124 +0x1d1
github.com/kiali/kiali/business.(*IstioValidationsService).isGatewayToNamespace(0x6353a0?)
	/home/fedora/go/src/github.com/kiali/kiali/business/istio_validations.go:597 +0x45
github.com/kiali/kiali/business.(*IstioValidationsService).getAllObjectCheckers(_, {{{0x0, 0x0}, {0x0, 0x0}, 0x0, {0x0, 0x0, 0x0}, 0x0, ...}, ...}, ...)
	/home/fedora/go/src/github.com/kiali/kiali/business/istio_validations.go:146 +0x37d
github.com/kiali/kiali/business.(*IstioValidationsService).GetValidations(0xc000279ca8, {0x23a19c8, 0xc000058068}, {0xc000844630, 0xf}, {0xc00170e454, 0x8}, {0x0, 0x0}, {0x0, ...})
	/home/fedora/go/src/github.com/kiali/kiali/business/istio_validations.go:122 +0x1365
github.com/kiali/kiali/handlers.IstioConfigList.func1({0xc00170e454?, 0x8}, 0xc000490430, 0xc000888de0)
	/home/fedora/go/src/github.com/kiali/kiali/handlers/istio_config.go:85 +0xf7
created by github.com/kiali/kiali/handlers.IstioConfigList
	/home/fedora/go/src/github.com/kiali/kiali/handlers/istio_config.go:82 +0x8a5
```

**Comment by jmazzitelli** [comment]
I'll take a look. @hhovsepy do you know what version of both Istio and OpenShift is this testing with?

**Comment by jmazzitelli** [comment]
FWIW: a very basic "install Istio 1.18.2, install bookinfo with traffic generator, install kiali 1.73-snapshot" does not show the error. Kiali starts up fine. So there is something specific to environment jenkins puts together that finds this bug in kiali.

**Comment by jmazzitelli** [comment]
quick replication:

1. Install Istio in an OpenShift cluster
2. Install bookinfo demo
3. edit `hack/run-kiali-config-template.yaml` so that these are set:
```yaml
deployment:
  accessible_namespaces: ["bookinfo"]
  cluster_wide_access: false
```
4. Start kiali locally via `hack/run-kiali.sh -kc current`
5. You will see the error occur when you submit a request via broswer: `xdg-open http://localhost:20001`

Error in logs will result (notice this is different than the original description, but I believe its the same thing):
```
2023/08/24 17:14:41 http: panic serving [::1]:49302: runtime error: invalid memory address or nil pointer dereference
goroutine 498 [running]:
net/http.(*conn).serve.func1()
	/home/jmazzite/bin/go-install/go/src/net/http/server.go:1854 +0xbf
panic({0x1d765a0, 0x3377ac0})
	/home/jmazzite/bin/go-install/go/src/runtime/panic.go:890 +0x263
github.com/kiali/kiali/kubernetes/cache.(*kubeCache).GetConfigMap(0xc00034a000, {0xc0001d5c00, 0xc}, {0x2089134, 0x5})
	/home/jmazzite/source/kiali/kiali/kubernetes/cache/kube_cache.go:554 +0x17d
github.com/kiali/kiali/business.(*NamespaceService).GetNamespaces(0xc00028f330, {0x23a1a58, 0xc000596630})
	/home/jmazzite/source/kiali/kiali/business/namespaces.go:98 +0x245
github.com/kiali/kiali/handlers.NamespaceList({0x2391860, 0xc000a26078}, 0xc000121000)
	/home/jmazzite/source/kiali/kiali/handlers/namespaces.go:22 +0x114
net/http.HandlerFunc.ServeHTTP(0x2094194?, {0x2391860?, 0xc000a26078?}, 0x7f215de3f8e8?)
	/home/jmazzite/bin/go-install/go/src/net/http/server.go:2122 +0x2f
```

**Comment by jmazzitelli** [comment]
https://github.com/kiali/kiali/blob/master/business/mesh.go#L323-L324
```go
// TODO: This will fail if cluster wide mode is not enabled.
services, err := kubeCache.GetServices("", kialiAppLabel)
```
You got that right! And by "fail" it means "puke a segfault" :)

Passing in an empty namespace will blow up the namespace cache lookup. We need to not make this call at all if not in cluster-wide mode.

**Comment by jmazzitelli** [comment]
I did a quick check of the code and it appears this is the only place where empty string is explicitly passed into any kube cache function (this assumes all cache variables have "cache" appended to the var name):

```
$ grep --exclude-dir frontend --exclude-dir _output -ERi 'cache.*""' *
business/services.go:			pods, err2 = kubeCache.GetPods(criteria.Namespace, "")
business/workloads.go:		pods, err = kialiCache.GetPods(criteria.Namespace, "")
business/mesh.go:	services, err := kubeCache.GetServices("", kialiAppLabel)
kubernetes/cache/kube_cache_test.go:	assert.False(kubeCache.isCached(""))
kubernetes/cache/kube_cache_test.go:	kialiCache.Refresh("")
kubernetes/cache/kube_cache_test.go:	kialiCache.Refresh("")
kubernetes/cache/kube_cache_test.go:	kialiCache.Refresh("")
kubernetes/cache/kube_cache_test.go:	vsListFromCache, err := kialiCache.GetVirtualServices("test", "")
kubernetes/cache/kube_cache_test.go:	pods, err := kialiCache.GetPods("test", "")
```
