### ISSUE TITLE
flaky test - seg fault in backend unit test

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#6521]
I saw this one time but never again; I cannot replicate it with `make -e GO_TEST_FLAGS="-race" test`. But even after examining the code for client_factory.go and registry_status.go, I still can't explain it, so I have a feeling there is an issue here that I can't see. I'm documenting this for future reference. In case someone else wants to look at it, feel free.

```
{"level":"info","time":"2023-08-24T22:34:28Z","message":"Adding a RegistryRefreshHandler"}
{"level":"debug","time":"2023-08-24T22:34:28Z","message":"[Kiali Cache] Using 'cluster' scoped Kiali Cache"}
{"level":"debug","time":"2023-08-24T22:34:28Z","message":"[Kiali Cache] Starting cluster-scoped informers"}
{"level":"info","time":"2023-08-24T22:34:28Z","message":"[Kiali Cache] Waiting for cluster-scoped cache to sync"}
{"level":"info","time":"2023-08-24T22:34:28Z","message":"[Kiali Cache] Started"}
{"level":"info","time":"2023-08-24T22:34:28Z","message":"[Kiali Cache] Kube cache is active for cluster: []"}
{"level":"trace","time":"2023-08-24T22:34:28Z","message":"Failed to call Istiod endpoint /debug/registryz error: unable to proxy Istiod pods. Make sure your Kubernetes API server has access to the Istio control plane through 8080 port"}
{"level":"debug","time":"2023-08-24T22:34:28Z","message":"Unable to read remote secret. It may or may not exist. Error: open /kiali-remote-secret/kiali: no such file or directory. Falling back to in cluster config"}
{"level":"error","time":"2023-08-24T22:34:28Z","message":"Error 'unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined' getting config for local cluster"}
{"level":"trace","time":"2023-08-24T22:34:28Z","message":"[Kiali Cache] Get [resource: ConfigMap] for [namespace: istio-system] [name: istio]"}
{"level":"trace","time":"2023-08-24T22:34:28Z","message":"No Istio discovery selectors defined."}
{"level":"trace","time":"2023-08-24T22:34:28Z","message":"[Kiali Cache] Get [resource: ConfigMap] for [namespace: istio-system] [name: istio]"}
{"level":"trace","time":"2023-08-24T22:34:28Z","message":"Failed to call Istiod endpoint /debug/configz error: unable to proxy Istiod pods. Make sure your Kubernetes API server has access to the Istio control plane through 8080 port"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x25a3d2a]

goroutine 7815 [running]:
github.com/kiali/kiali/kubernetes.(*clientFactory).GetSAHomeClusterClient(0x0)
	/home/runner/work/kiali/kiali/kubernetes/client_factory.go:456 +0x2a
github.com/kiali/kiali/business.getSAClient()
	/home/runner/work/kiali/kiali/business/registry_status.go:298 +0x5a
github.com/kiali/kiali/business.(*RegistryStatusService).getRegistryConfigurationUsingKialiSA(0xc000e2f680?)
	/home/runner/work/kiali/kiali/business/registry_status.go:320 +0x2a
github.com/kiali/kiali/business.(*RegistryStatusService).refreshRegistryStatus.func1()
	/home/runner/work/kiali/kiali/business/registry_status.go:253 +0x190
created by github.com/kiali/kiali/business.(*RegistryStatusService).refreshRegistryStatus
	/home/runner/work/kiali/kiali/business/registry_status.go:250 +0x392
FAIL	github.com/kiali/kiali/business	6.747s
```

The line numbers will match up looking at this commit: https://github.com/kiali/kiali/tree/c444a75a923597b0fcc64b057ecc813f5c8aaae5

The full test logs are currently found here: https://github.com/kiali/kiali/actions/runs/5969562704/job/16195629068

**Comment by jshaughn** [comment]
Closing as not reproducible.  Can re-open as needed.
