### ISSUE TITLE
Unable to reach API Server 'istio APIs and resources are not present in cluster [Kubernetes]'

### ISSUE THREAD

**Issue by ConnorsApps** [kiali/kiali#6598]
## versions
- istio `1.18.2`
- kiali-server `1.73.0`
- k8s `1.28.1`

## Problem
The Kiali dashboard on the console wasn't loading and the pod logs were the following.
```
kiali {"level":"info","time":"2023-09-09T13:08:46Z","message":"Adding a RegistryRefreshHandler"}
kiali 2023-09-09T13:08:46Z INF Kiali: Version: v1.73.0, Commit: 2e54c9e768905ad47338a1641c6777c3f2fbcc9c, Go: 1.20.5
kiali 2023-09-09T13:08:46Z WRN Cannot resolve local cluster name. Err: Get "https://172.16.16.1:443/apis/apps/v1/namespaces/istio-system/deployments/istiod": dial tcp 172.16.16.1:443: connect: connection refused. Falling back to [Kubernetes]
kiali 2023-09-09T13:08:46Z INF Using authentication strategy [token]
kiali 2023-09-09T13:08:46Z INF Some validation errors will be ignored [KIA1301]. If these errors do occur, they will still be logged. If you think the validation errors you see are incorrect, please report them to the Kiali team if you have not done so already and provide the details of your scenario. This will keep Kiali validations strong for the whole community.
kiali 2023-09-09T13:08:46Z INF Initializing Kiali Cache
kiali 2023-09-09T13:08:46Z INF Adding a RegistryRefreshHandler
kiali 2023-09-09T13:08:46Z WRN Error checking Istio API configuration: Get "https://172.16.16.1:443/apis/networking.istio.io": dial tcp 172.16.16.1:443: connect: connection refused
kiali 2023-09-09T13:08:46Z WRN Error checking Kubernetes Gateway API configuration: Get "https://172.16.16.1:443/apis/gateway.networking.k8s.io": dial tcp 172.16.16.1:443: connect: connection refused
kiali 2023-09-09T13:08:46Z INF [Kiali Cache] Waiting for cluster-scoped cache to sync
kiali W0909 13:08:46.861412       1 reflector.go:533] pkg/mod/k8s.io/client-go@v0.27.2/tools/cache/reflector.go:231: failed to list *v1.Pod: Get "https://172.16.16.1:443/api/v1/pods?limit=500&resourceVersion=0": dial tcp 172.16.16.1:443: connect: connection refused
kiali W0909 13:08:46.861427       1 reflector.go:533] pkg/mod/k8s.io/client-go@v0.27.2/tools/cache/reflector.go:231: failed to list *v1.ReplicaSet: Get "https://172.16.16.1:443/apis/apps/v1/replicasets?limit=500&resourceVersion=0": dial tcp 172.16.16.1:443: connect: connection refused
kiali E0909 13:08:46.861534       1 reflector.go:148] pkg/mod/k8s.io/client-go@v0.27.2/tools/cache/reflector.go:231: Failed to watch *v1.Pod: failed to list *v1.Pod: Get "https://172.16.16.1:443/api/v1/pods?limit=500&resourceVersion=0": dial tcp 172.16.16.1:443: connect: connection refused
kiali E0909 13:08:46.861531       1 reflector.go:148] pkg/mod/k8s.io/client-go@v0.27.2/tools/cache/reflector.go:231: Failed to watch *v1.ReplicaSet: failed to list *v1.ReplicaSet: Get "https://172.16.16.1:443/apis/apps/v1/replicasets?limit=500&resourceVersion=0": dial tcp 172.16.16.1:443: connect: connection refused
kiali W0909 13:08:46.861948       1 reflector.go:533] pkg/mod/k8s.io/client-go@v0.27.2/tools/cache/reflector.go:231: failed to list *v1.StatefulSet: Get "https://172.16.16.1:443/apis/apps/v1/statefulsets?limit=500&resourceVersion=0": dial tcp 172.16.16.1:443: connect: connection refused
kiali E0909 13:08:46.862054       1 reflector.go:148] pkg/mod/k8s.io/client-go@v0.27.2/tools/cache/reflector.go:231: Failed to watch *v1.StatefulSet: failed to list *v1.StatefulSet: Get "https://172.16.16.1:443/apis/apps/v1/statefulsets?limit=500&resourceVersion=0": dial tcp 172.16.16.1:443: connect: connection refused
kiali W0909 13:08:46.862104       1 reflector.go:533] pkg/mod/k8s.io/client-go@v0.27.2/tools/cache/reflector.go:231: failed to list *v1.Endpoints: Get "https://172.16.16.1:443/api/v1/endpoints?limit=500&resourceVersion=0": dial tcp 172.16.16.1:443: connect: connection refused
kiali W0909 13:08:46.862149       1 reflector.go:533] pkg/mod/k8s.io/client-go@v0.27.2/tools/cache/reflector.go:231: failed to list *v1.Service: Get "https://172.16.16.1:443/api/v1/services?limit=500&resourceVersion=0": dial tcp 172.16.16.1:443: connect: connection refused
kiali E0909 13:08:46.862210       1 reflector.go:148] pkg/mod/k8s.io/client-go@v0.27.2/tools/cache/reflector.go:231: Failed to watch *v1.Endpoints: failed to list *v1.Endpoints: Get "https://172.16.16.1:443/api/v1/endpoints?limit=500&resourceVersion=0": dial tcp 172.16.16.1:443: connect: connection refused
kiali W0909 13:08:46.862149       1 reflector.go:533] pkg/mod/k8s.io/client-go@v0.27.2/tools/cache/reflector.go:231: failed to list *v1.Deployment: Get "https://172.16.16.1:443/apis/apps/v1/deployments?limit=500&resourceVersion=0": dial tcp 172.16.16.1:443: connect: connection refused
kiali E0909 13:08:46.862224       1 reflector.go:148] pkg/mod/k8s.io/client-go@v0.27.2/tools/cache/reflector.go:231: Failed to watch *v1.Service: failed to list *v1.Service: Get "https://172.16.16.1:443/api/v1/services?limit=500&resourceVersion=0": dial tcp 172.16.16.1:443: connect: connection refused
kiali E0909 13:08:46.862262       1 reflector.go:148] pkg/mod/k8s.io/client-go@v0.27.2/tools/cache/reflector.go:231: Failed to watch *v1.Deployment: failed to list *v1.Deployment: Get "https://172.16.16.1:443/apis/apps/v1/deployments?limit=500&resourceVersion=0": dial tcp 172.16.16.1:443: connect: connection refused
kiali W0909 13:08:46.862406       1 reflector.go:533] pkg/mod/k8s.io/client-go@v0.27.2/tools/cache/reflector.go:231: failed to list *v1.ConfigMap: Get "https://172.16.16.1:443/api/v1/configmaps?limit=500&resourceVersion=0": dial tcp 172.16.16.1:443: connect: connection refused
kiali W0909 13:08:46.862411       1 reflector.go:533] pkg/mod/k8s.io/client-go@v0.27.2/tools/cache/reflector.go:231: failed to list *v1.DaemonSet: Get "https://172.16.16.1:443/apis/apps/v1/daemonsets?limit=500&resourceVersion=0": dial tcp 172.16.16.1:443: connect: connection refused
kiali E0909 13:08:46.862498       1 reflector.go:148] pkg/mod/k8s.io/client-go@v0.27.2/tools/cache/reflector.go:231: Failed to watch *v1.DaemonSet: failed to list *v1.DaemonSet: Get "https://172.16.16.1:443/apis/apps/v1/daemonsets?limit=500&resourceVersion=0": dial tcp 172.16.16.1:443: connect: connection refused
kiali E0909 13:08:46.862510       1 reflector.go:148] pkg/mod/k8s.io/client-go@v0.27.2/tools/cache/reflector.go:231: Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: Get "https://172.16.16.1:443/api/v1/configmaps?limit=500&resourceVersion=0": dial tcp 172.16.16.1:443: connect: connection refused
kiali 2023-09-09T13:08:48Z INF [Kiali Cache] Started
kiali 2023-09-09T13:08:48Z INF [Kiali Cache] Kube cache is active for cluster: [Kubernetes]
kiali 2023-09-09T13:08:48Z INF Server endpoint will start at [:20001/kiali]
kiali 2023-09-09T13:08:48Z INF Server endpoint will serve static content from [/opt/kiali/console]
kiali 2023-09-09T13:08:48Z INF Starting Metrics Server on [:9090]
kiali 2023-09-09T13:10:08Z INF [Prom Cache] Enabled
kiali 2023-09-09T13:10:08Z ERR Failed to fetch Prometheus flags: bad_response: readObjectStart: expect { or n, but found r, error found in #1 byte of ...|remoteAddr:|..., bigger context ...|remoteAddr: "127.0.0.6:41899"; requestURI: /api/v1/|...
kiali 2023-09-09T13:10:08Z ERR error from Grafana (401): Unauthorized
kiali 2023-09-09T13:10:18Z ERR Error fetching Istio Config per namespace istio-system: istio APIs and resources are not present in cluster [Kubernetes]
kiali 2023-09-09T13:10:18Z ERR istio APIs and resources are not present in cluster [Kubernetes]
kiali 2023-09-09T13:11:16Z WRN Could not read the session: error when restoring the session - failed to decrypt: cipher: message authentication failed
kiali 2023-09-09T13:11:27Z ERR Failed to fetch Prometheus flags: bad_response: readObjectStart: expect { or n, but found r, error found in #1 byte of ...|remoteAddr:|..., bigger context ...|remoteAddr: "127.0.0.6:56061"; requestURI: /api/v1/|...
kiali 2023-09-09T13:11:28Z ERR Error fetching Istio Config per namespace istio-system: istio APIs and resources are not present in cluster [Kubernetes]
kiali 2023-09-09T13:11:28Z ERR Error fetching Istio Config per namespace istio-system: istio APIs and resources are not present in cluster [Kubernetes]
kiali 2023-09-09T13:11:28Z ERR istio APIs and resources are not present in cluster [Kubernetes]
kiali 2023-09-09T13:11:28Z ERR istio APIs and resources are not present in cluster [Kubernetes]
kiali 2023-09-09T13:15:21Z ERR Failed to fetch Prometheus flags: bad_response: readObjectStart: expect { or n, but found r, error found in #1 byte of ...|remoteAddr:|..., bigger context ...|remoteAddr: "127.0.0.6:55373"; requestURI: /api/v1/|...
kiali 2023-09-09T13:15:25Z ERR error from Grafana (401): Unauthorized
kiali 2023-09-09T13:15:25Z ERR error from Grafana (401): Unauthorized
kiali 2023-09-09T13:15:25Z ERR error from Grafana (401): Unauthorized
kiali 2023-09-09T13:15:28Z ERR istio APIs and resources are not present in cluster [Kubernetes]: goroutine 5931 [running]:
kiali runtime/debug.Stack()
kiali     /opt/hostedtoolcache/go/1.20.5/x64/src/runtime/debug/stack.go:24 +0x65
kiali github.com/kiali/kiali/handlers.handlePanic({0x2391840, 0xc000b1f668})
kiali     /home/runner/work/kiali/kiali/handlers/graph.go:86 +0x219
kiali panic({0x1c74180, 0xc00299c030})
kiali     /opt/hostedtoolcache/go/1.20.5/x64/src/runtime/panic.go:884 +0x213
kiali github.com/kiali/kiali/graph.CheckError(...)
kiali     /home/runner/work/kiali/kiali/graph/util.go:38
kiali github.com/kiali/kiali/graph/telemetry/istio/appender.addBadging(0x8?, 0xc001d24cc0, 0xc000468c30)
kiali     /home/runner/work/kiali/kiali/graph/telemetry/istio/appender/istio_details.go:66 +0x506
kiali github.com/kiali/kiali/graph/telemetry/istio/appender.IstioAppender.AppendGraph({0x2089134?}, 0xc001d25260, 0xc00183bbc0?, 0xc000468c30)
kiali     /home/runner/work/kiali/kiali/graph/telemetry/istio/appender/istio_details.go:49 +0x7e
kiali github.com/kiali/kiali/graph/telemetry/istio.BuildNamespacesTrafficMap({_, _}, {0xc001d24ae0, {0x0, {0xc000018c40, 0x7, 0x7}}, 0x0, 0x1, 0xc001d24990, ...}, ...)
kiali     /home/runner/work/kiali/kiali/graph/telemetry/istio/istio.go:80 +0x6a3
kiali github.com/kiali/kiali/graph/api.graphNamespacesIstio({_, _}, _, _, {{0x208eb3f, 0x9}, {0x2089134, 0x5}, {{0xc000878a79, 0x15}, ...}, ...})
kiali     /home/runner/work/kiali/kiali/graph/api/api.go:52 +0x126
kiali github.com/kiali/kiali/graph/api.GraphNamespaces({_, _}, _, {{0x208eb3f, 0x9}, {0x2089134, 0x5}, {{0xc000878a79, 0x15}, {0xdf8475800, ...}}, ...})
kiali     /home/runner/work/kiali/kiali/graph/api/api.go:33 +0x2fb
kiali github.com/kiali/kiali/handlers.GraphNamespaces({0x2391840, 0xc000b1f668}, 0xc0027a1700)
kiali     /home/runner/work/kiali/kiali/handlers/graph.go:51 +0x165
kiali net/http.HandlerFunc.ServeHTTP(0x20970a6?, {0x2391840?, 0xc000b1f668?}, 0x7f664543a880?)
kiali     /opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2122 +0x2f
kiali github.com/kiali/kiali/routing.metricHandler.func1({0x23a0600?, 0xc000018bd0}, 0xc001c71901?)
kiali     /home/runner/work/kiali/kiali/routing/router.go:145 +0x13b
kiali net/http.HandlerFunc.ServeHTTP(0x23a1a38?, {0x23a0600?, 0xc000018bd0?}, 0xc001c71980?)
kiali     /opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2122 +0x2f
kiali github.com/kiali/kiali/handlers.AuthenticationHandler.Handle.func1({0x23a0600, 0xc000018bd0}, 0xc0027a1400)
kiali     /home/runner/work/kiali/kiali/handlers/authentication.go:79 +0x3fd
kiali net/http.HandlerFunc.ServeHTTP(0x23a1a38?, {0x23a0600?, 0xc000018bd0?}, 0x2374d30?)
kiali     /opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2122 +0x2f
kiali github.com/kiali/kiali/server.plainHttpMiddleware.func1({0x23a0600?, 0xc000018bd0?}, 0xc001d242a0?)
kiali     /home/runner/work/kiali/kiali/server/server.go:157 +0x65
kiali net/http.HandlerFunc.ServeHTTP(0xc0027a1300?, {0x23a0600?, 0xc000018bd0?}, 0x2?)
kiali     /opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2122 +0x2f
kiali github.com/gorilla/mux.(*Router).ServeHTTP(0xc000157440, {0x23a0600, 0xc000018bd0}, 0xc0027a1200)
kiali     /home/runner/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
kiali github.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1({0x23a04b0, 0xc0013ced20}, 0x0?)
kiali     /home/runner/go/pkg/mod/github.com/!n!y!times/gziphandler@v1.1.1/gzip.go:336 +0x24e
kiali net/http.HandlerFunc.ServeHTTP(0xc000999480?, {0x23a04b0?, 0xc0013ced20?}, 0x40d92a?)
kiali     /opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2122 +0x2f
kiali net/http.(*ServeMux).ServeHTTP(0xc000878a20?, {0x23a04b0, 0xc0013ced20}, 0xc0027a1200)
kiali     /opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2500 +0x149
kiali net/http.serverHandler.ServeHTTP({0xc001f5b8f0?}, {0x23a04b0, 0xc0013ced20}, 0xc0027a1200)
kiali     /opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2936 +0x316
kiali net/http.(*conn).serve(0xc001f88ab0, {0x23a1a38, 0xc000cf0390})
kiali     /opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:1995 +0x612
kiali created by net/http.(*Server).Serve
kiali     /opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:3089 +0x5ed
kiali 
```
After troubleshooting turned out the issue was simply the istio sidecar coming online before the main `kiali-server` container.

## Temporary Solution
Adding a wait annotation for the sidecar to become available. 
```yaml
deployment:
  pod_annotations:
    proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
```
## Suggested Long Term Solution
Maybe there should be retries and timeouts added.

**Comment by mmiara** [comment]
I am on similar versions - istio 1.18.2, kiali 1.72.0, and k8s 1.26 - and seeing the same issue. The only helpful message is both in the Kiali dashboard as an alert, and in the kiali pod:
```
istio APIs and resources are not present in cluster [Kubernetes]
```
I added the proxy config, and after redeploying, it seems that it takes a long while before this message goes away and I can view the graph, application, and workload sections of the Kiali dashboard. Any other ideas why this could be happening/solutions?

**Comment by jshaughn** [comment]
I'm not exactly sure why this would be tied to sidecars coming online before app code, in the pods.  It seems more related to Kiali running and not being able to reach the Istio infrastructure, primarily the Istio API (debug endpoints offerered by istiod), but also it seems prometheus is unavailable for some period.   Is Kiali not deployed with the control plane, or somehow started prior to the mesh?

**Comment by KarstenSiemer** [comment]
I have the same problem and adding this:
```yaml
deployment:
  pod_annotations:
    proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
```
Also did fix the problem for me. Something wrong and I have no idea how to debug it to be honest.
Thanks @ConnorsApps! I was looking around for 2 days...

**Comment by jshaughn** [comment]
To be clear, to which deployments did you add that annotation?   Did you also depliy Kiali via helm?

cc @jmazzitelli @nrfox

**Comment by ConnorsApps** [comment]
> To be clear, to which deployments did you add that annotation?   Did you also depliy Kiali via helm?
> 
> 
> 
> cc @jmazzitelli @nrfox 

I can't speak for them but I deployed it via helm a long time after I already was using Istio.

The annotations I provided were values for the Kiali helm chart.

**Comment by nrfox** [comment]
@ConnorsApps you mentioned:

> After troubleshooting turned out the issue was simply the istio sidecar coming online before the main kiali-server container.

Does this mean you are running the istio sidecar inside the kiali pod? If so, I'm not sure that's supported, perhaps for this reason. @jshaughn?

If you run Kiali without the istio sidecar it should work fine. @jmazzitelli I think adding the `sidecar.istio.io/inject: "false"` annotation to the Kiali helm chart would prevent issues like this.

**Comment by jmazzitelli** [comment]
We actually support that so people can put Kiali in the mesh (typically for securing the Kiali UI in the mesh mTLS setup). See FAQ:  https://kiali.io/docs/faq/installation/#how-can-i-inject-an-istio-sidecar-in-the-kiali-pod

**Comment by ConnorsApps** [comment]
I'm using istio sidecar injection mainly to use [virtual services](https://istio.io/latest/docs/reference/config/networking/virtual-service/) for everything in my clusters.  [Istio ambient mesh](https://istio.io/latest/docs/ops/ambient/getting-started/) will solve the issue by removing the need for a sidecar.

I've had a variety of issues using ambient mesh and I suspect it'll be awhile before it's extensively documented and used in production.

I might dig into this bit eventually. I've seen the [sidecar startup](https://istio.io/latest/docs/ops/common-problems/injection/#pod-or-containers-start-with-network-issues-if-istio-proxy-is-not-ready) problem a lot with other applications.

**Comment by jshaughn** [comment]
@jmazzitelli It sounds like we should update the FAQ as the action to address this issue.  Maybe add:

```
deployment:
  pod_annotations:
    proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
```

**Comment by jmazzitelli** [comment]
I added the docs label to this issue - we should update kiali.io docs to include that `deployment.pod_annotations`.

**Comment by Hronom** [comment]
Maybe even add it by default somehow, since Kiali is for Istio only. I also got in the same trouble.
This fixes helped me:
* https://github.com/kiali/kiali/issues/6598#issuecomment-1747574361
* https://github.com/kiali/kiali/issues/6598#issuecomment-1750817053
