### ISSUE TITLE
updating from 1.63.2 to 1.74.0 fails

### ISSUE THREAD

**Issue by mikebell90** [kiali/kiali#6759]
k8s 1.25, Istio 1.19.3

[failure.zip](https://github.com/kiali/kiali/files/13058112/failure.zip)

Quite frankly the kiali-operator while very detailed is very hard to read for failures

**Comment by jmazzitelli** [comment]
Need juuuust a bit more info :)

How did you install the Kiali Operator? Helm ? OLM?

Where did you get the Kiali Operator (alot of  people who have problems are getting the helm charts from places other than the Kiali team repo).?

What is failing to upgrade? The operator or the Kiali Server?

What does the Kiali CR look like? Does the `status` field have any errors in it (that's usually the place you look to see what the main error is).

**Comment by mikebell90** [comment]
We installed it via helm/github action.

```
---
name: kiali

run-name: ${{ github.workflow }} [${{ github.event.inputs.clustername }}]
on:
  workflow_dispatch:
    inputs:
      clustername:
        description: K8S cluster name where to deploy
        type: environment
        required: true

defaults:
  run:
    shell: bash

env:
  NAMESPACE: istio-monitoring

jobs:
  deploy:
    if: github.event.inputs.clustername != ''
    runs-on: ${{github.event.inputs.clustername}}
    environment: ${{github.event.inputs.clustername}}
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
      with:
        repository: opentable/ot-kubernetes-deploy-templates
        ssh-key: ${{ secrets.OT_DEVOPS_KEY }}
        ssh-strict: false

    - name: Add repo to Helm
      run : helm repo add kiali https://kiali.org/helm-charts

    - name: Deploy with Helm
      run: |
       helm upgrade --install --wait --timeout 30m  \
        --namespace $NAMESPACE \
        --set cr.spec.external_services.grafana.url="http://istio-grafana.${{github.event.inputs.clustername}}.k8s.otenv.com/" \
        --create-namespace \
        --version 1.63.2 \
        kiali-operator \
        kiali/kiali-operator \
        -f ./ot-helm-values/kiali/istio-kiali.yaml \
        -f ./ot-helm-values/kiali/${{github.event.inputs.clustername}}.yaml \

  set_client_secret:
    runs-on: ${{github.event.inputs.clustername}}
    if: ${{ success() }}
    needs: deploy
    env:
      DEX_CLIENT_STATIC_PASSWD: ${{ secrets.DEX_CLIENT_STATIC_PASSWD }}
    steps:
      - name: Set client secret
        run: |
          kubectl create secret generic kiali \
          --from-literal="oidc-secret=$DEX_CLIENT_STATIC_PASSWD" \
          -n $NAMESPACE --dry-run \
          -o yaml | kubectl apply -f - \

  external_name:
    runs-on: ${{github.event.inputs.clustername}}
    if: ${{ success() }}
    needs: deploy
    steps:
      - name: Wait for kiali operator
        run: |
          kubectl wait --for=condition=Successful kiali kiali -n $NAMESPACE
           kubectl -n $NAMESPACE label svc kiali needs-externalname=yes
```

- All I f did is change the version above from 1.63.2 to 1.74.0

The values file for above is

```
# Kiali operator default values reference
# https://github.com/kiali/helm-charts/blob/master/kiali-operator/values.yaml

# Kiali CR reference
# https://kiali.io/docs/configuration/kialis.kiali.io/

allowAdHocKialiImage: true
image:
  repo: dockerhub.otenv.com/kiali/kiali-operator

spec:
  istio_namespace: "istio-system"
# metrics.enabled: set to true if you want Prometheus to collect metrics from the operator
metrics:
  enabled: true

# Defines where the operator will look for Kiali CR resources. "" means "all namespaces".
watchNamespace: "istio-monitoring"


# For what a Kiali CR spec can look like, see:
# https://github.com/kiali/kiali-operator/blob/master/deploy/kiali/kiali_cr.yaml
cr:
  create: true
  name: kiali
  # If you elect to create a Kiali CR (--set cr.create=true)
  # and the operator is watching all namespaces (--set watchNamespace="")
  # then this is the namespace where the CR will be created (the default will be the operator namespace).
  namespace: "istio-monitoring"

  # Annotations to place in the Kiali CR metadata.
  annotations: {}

  spec:
    istio_namespace: "istio-system"
    deployment:
      image_name: "dockerhub.otenv.com/kiali/kiali"
      resources:
        requests:
          cpu: "500m"
          memory: "1536Mi"
      view_only_mode: true
      accessible_namespaces: ["**"]
      additional_service_yaml:
        ports:
          - name: http
            protocol: TCP
            port: 80
            targetPort: 20001
          - name: http-metrics
            protocol: TCP
            port: 9090
            targetPort: 9090

    server:
      web_port: 443

    auth:
      strategy: openid
      openid:
        additional_request_params:
          prompt: login
        disable_rbac: true
        scopes:
          - "openid"
          - "email"
          - "groups"
        insecure_skip_verify_tls: true
        client_id: "k8s-dex-app"
        username_claim: "email"

    api:
      namespaces:
        exclude:
        - "^kube-.*"
        - "^gm-iop-.*"
        - "^monitoring"
        - velero
        - rook-ceph
        - kuberhealthy
        - fleet-system
        - system-upgrade
        - keda
        - komodor
        - vpa
        - build-agents
        - cert-manager
        - ot-kube-system

    external_services:
      prometheus:
        url: http://feeder-mesh-prometheus/
        cache_duration: 300
        cache_enabled: true
        cache_expiration: 600

      grafana:
        enabled: true
        in_cluster_url: "http://istio-grafana/"

      # Confuguration used to access the Tracing (Jaeger) dashboards
      tracing:
        enabled: false # Setting to false as it tries to reach Jaeger otherwise

      istio:
        component_status:
          components:
          - app_label: "istiod"
            namespace: istio-system
          - app_label: "istio-ingressgateway"
            namespace: istio-gateways
          - app_label: "istio-eastwestgateway"
            namespace: istio-gateways
          enabled: true

    istio_labels:
      injection_label_name: "sidecar.istio.io/inject"
      injection_label_rev: "istio.io/rev"

    kubernetes_config:
      cache_duration: 600
      cache_enabled: true
      cache_istio_types:
      - "AuthorizationPolicy"
      - "DestinationRule"
      - "EnvoyFilter"
      - "Gateway"
      - "PeerAuthentication"
      - "RequestAuthentication"
      - "ServiceEntry"
      - "Sidecar"
      - "VirtualService"
      - "WorkloadEntry"
      - "WorkloadGroup"
      cache_namespaces:
      - ".*"
      cache_token_namespace_duration: 10
```

- dockerhub.otenv.com is a selective pull through cache
- The operator reports FAILURE (nothing more in status), so the server never gets upgraded.

**Comment by mikebell90** [comment]
We also tried
- Helm uninstall kiali-operator
- Delete the configmap and kiali deployment
- Reinstall

Same results

**Comment by jmazzitelli** [comment]
The error is this.. seems like Python is blowing up trying to remove the kiali namespace label from a namespace.

```
TASK [default/kiali-deploy : Remove Kiali label from namespaces that Kiali no longer has access to] ***
An exception occurred during task execution. To see the full traceback, use -vvv. The error was:         ^
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):
File "/opt/ansible/.ansible/tmp/ansible-tmp-1697831054.6563983-670-241944077875114/AnsiballZ_k8s.py", line 102, in <module>
_ansiballz_main()
File "/opt/ansible/.ansible/tmp/ansible-tmp-1697831054.6563983-670-241944077875114/AnsiballZ_k8s.py", line 94, in _ansiballz_main
invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
File "/opt/ansible/.ansible/tmp/ansible-tmp-1697831054.6563983-670-241944077875114/AnsiballZ_k8s.py", line 40, in invoke_module
runpy.run_module(mod_name='ansible_collections.kubernetes.core.plugins.modules.k8s', init_globals=None, run_name='__main__', alter_sys=True)
File "/usr/lib64/python3.8/runpy.py", line 207, in run_module
return _run_module_code(code, init_globals, run_name, mod_spec)
File "/usr/lib64/python3.8/runpy.py", line 97, in _run_module_code
_run_code(code, mod_globals, init_globals,
File "/usr/lib64/python3.8/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/tmp/ansible_k8s_payload_wxhha__2/ansible_k8s_payload.zip/ansible_collections/kubernetes/core/plugins/modules/k8s.py", line 397, in <module>
File "/tmp/ansible_k8s_payload_wxhha__2/ansible_k8s_payload.zip/ansible_collections/kubernetes/core/plugins/modules/k8s.py", line 393, in main
File "/tmp/ansible_k8s_payload_wxhha__2/ansible_k8s_payload.zip/ansible_collections/kubernetes/core/plugins/modules/k8s.py", line 376, in execute_module
File "/tmp/ansible_k8s_payload_wxhha__2/ansible_k8s_payload.zip/ansible_collections/kubernetes/core/plugins/module_utils/common.py", line 503, in set_resource_definitions
File "/tmp/ansible_k8s_payload_wxhha__2/ansible_k8s_payload.zip/ansible_collections/kubernetes/core/plugins/module_utils/common.py", line 503, in <listcomp>
File "/usr/local/lib64/python3.8/site-packages/yaml/__init__.py", line 93, in load_all
yield loader.get_data()
File "/usr/local/lib64/python3.8/site-packages/yaml/constructor.py", line 45, in get_data
return self.construct_document(self.get_node())
File "/usr/local/lib64/python3.8/site-packages/yaml/composer.py", line 27, in get_node
return self.compose_document()
File "/usr/local/lib64/python3.8/site-packages/yaml/composer.py", line 55, in compose_document
node = self.compose_node(None, None)
File "/usr/local/lib64/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
node = self.compose_mapping_node(anchor)
File "/usr/local/lib64/python3.8/site-packages/yaml/composer.py", line 133, in compose_mapping_node
item_value = self.compose_node(node, item_key)
File "/usr/local/lib64/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
node = self.compose_mapping_node(anchor)
File "/usr/local/lib64/python3.8/site-packages/yaml/composer.py", line 133, in compose_mapping_node
item_value = self.compose_node(node, item_key)
File "/usr/local/lib64/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
node = self.compose_mapping_node(anchor)
File "/usr/local/lib64/python3.8/site-packages/yaml/composer.py", line 127, in compose_mapping_node
while not self.check_event(MappingEndEvent):
File "/usr/local/lib64/python3.8/site-packages/yaml/parser.py", line 98, in check_event
self.current_event = self.state()
File "/usr/local/lib64/python3.8/site-packages/yaml/parser.py", line 425, in parse_block_mapping_first_key
return self.parse_block_mapping_key()
File "/usr/local/lib64/python3.8/site-packages/yaml/parser.py", line 438, in parse_block_mapping_key
raise ParserError("while parsing a block mapping", self.marks[-1],
yaml.parser.ParserError: while parsing a block mapping
expected <block end>, but found ':'
in "<unicode string>", line 7, column 5:
: null
^
", "module_stdout": "", "msg": "MODULE FAILURE
See stdout/stderr for the exact error", "rc": 1}
```

**Comment by mikebell90** [comment]
And it will continue to fail - since there are no namespaces with a kiali label and never have been ;) 
But the error is what I mean. This really says very little as an error message. It's probably an unfortunate consequence of wrapping in ansible, but there I speculate.

**Comment by jmazzitelli** [comment]
`repo: dockerhub.otenv.com/kiali/kiali-operator`

This is not a Kiali Operator container image coming from quay. It looks to be some third party binary that we have no control of and no idea if it matches the binary on quay.io that the Kiali team published.

Please try with the Kiali Operator container that is shipped by the Kiali team - found here: https://quay.io/repository/kiali/kiali-operator?tab=tags

**Comment by mikebell90** [comment]
Also can you explain "Remove Kiali label from namespaces that Kiali no longer has access to" - even if we had labels, the sentence is poorly worded in that of course you can remove things from resourcses you don't have access.

**Comment by mikebell90** [comment]
It is the quay. as I explained this is a passthrough Cache. We cannot for security reasons ever directly use quay. But this is in all essence just an artifactor JCR passthrough.

**Comment by jmazzitelli** [comment]
Of course, I have no way to validate that :) Several times in the past we've had community members pulling in images that come from some other repos and it turns out they were using images that were faulty and caused failures. Which is why I ask you validate that.

Otherwise, we would need replication procedures we can run over here to see the error. So if you have concrete steps and replication procedures which reproduce the error, we can try over here and see what is going on.

**Comment by jmazzitelli** [comment]
> "Remove Kiali label from namespaces that Kiali no longer has access to"

When you install Kiali withi accessible namespaces that is NOT `['**']`, the Kiali operator will stamp the namespaces Kiali has access to with kiali-specific labels. When you change accessible namespaces and some namespaces are no longer accessible to the Kiali Server, the Operator will remove those labels. That is what is failing.

**Comment by jmazzitelli** [comment]
This is the ansible task that is failing: https://github.com/kiali/kiali-operator/blob/master/roles/default/kiali-deploy/tasks/main.yml#L866-L886

**Comment by jmazzitelli** [comment]
I think it has to do with api.namespace.label_selector_include (this was a new setting, basically renaming the old label_selector setting. this [change](https://github.com/kiali/kiali-operator/commit/e973a4f56f8fb130468408b4ac21a5ba4badd629) happened between the 1.63 you were using and the 1.74 you are using now).

Though I can see where the error happens or how to workaround it. But I suspect it has to do with this change.

**Comment by mikebell90** [comment]
Do you have a suggested bisect install strategy?

**Comment by jmazzitelli** [comment]
Try to run this with Kiali Operator 1.65.0 and then with 1.66.0. 

If it involves what I think it does, 1.65 will work, 1.66 will fail. If that is true, go from there and come up with some test procedures to figure out how to replicate the error.

If all else fails, try this and see if it works around the error. In the Kiali CR, set this:

```yaml
api:
  namespaces:
    label_selector_include: "kiali.io/member-of=istio-system"
```

**Comment by jmazzitelli** [comment]
I'm almost positive the bug is here ... somewhere. I can't see why. Thought we had tests for this. But it looks like when upgrading, things are breaking because label_selector_include didn't exist in the older version you have, but is in the new version.

So I'm somewhat confident that if you set `api.namespaces.label_selector_include` to `"kiali.io/member-of=istio-system"` in the Kiali CR, it will get you over the hump. If that still doesn't work, go in the Kiali  ConfigMap (which you have if you still have the old Kiali Server installed) and add that `api.namespaces.label_selector_include` to it. Then see if the Kiali CR reconciles.

Once it reconciles and the Kiali Server upgrades to 1.74, this problem should go away, and you likely can remove that setting from future Kiali CRs.

I haven't tested any of this, because I don't have real replication procedures to actually see it happen, but reading the code, I think this is it.

**Comment by mikebell90** [comment]
- both 1.65 and 1.66.1 succeeded.

will follow up more on monday.

**Comment by mikebell90** [comment]
nope no go

1.65 - installls.
1.66-1.70 don't exist in quay (checked personally)
1.71-1.75 fail

editing kiali cr to add: doesn't work
editing kiali cm to add: doesn't work
removing all excludions (empty array) doesn't work

**Comment by jmazzitelli** [comment]
> 1.66-1.70 don't exist in quay (checked personally)

Kiali Operator versions 1.66 through 1.70 definitely do exist in quay.io

I see them all in https://quay.io/repository/kiali/kiali-operator?tab=tags

When I pull them all via this command:

```
for v in v1.66 v1.67 v1.68 v1.69 v1.70; do podman pull quay.io/kiali/kiali-operator:$v; done
```

All pull successfully.

When I run them all, all run successfully:

```
$ for v in v1.66 v1.67 v1.68 v1.69 v1.70; do echo "===RUN $v==="; podman run -it quay.io/kiali/kiali-operator:$v; echo; done
===RUN v1.66===
{"level":"info","ts":1698080045.5748808,"logger":"cmd","msg":"Version","Go Version":"go1.18.8","GOOS":"linux","GOARCH":"amd64","ansible-operator":"v1.25.0","commit":"3d4eb4b2de4b68519c8828f2289c2014979ccf2a"}
{"level":"error","ts":1698080045.5750232,"logger":"cmd","msg":"Failed to get config.","error":"invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable","errorCauses":[{"error":"no configuration has been provided, try setting KUBERNETES_MASTER environment variable"}],"stacktrace":"github.com/operator-framework/operator-sdk/internal/cmd/ansible-operator/run.run\n\t/workspace/internal/cmd/ansible-operator/run/cmd.go:110\ngithub.com/operator-framework/operator-sdk/internal/cmd/ansible-operator/run.NewCmd.func1\n\t/workspace/internal/cmd/ansible-operator/run/cmd.go:80\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:920\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:1040\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:968\nmain.main\n\t/workspace/cmd/ansible-operator/main.go:40\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}

===RUN v1.67===
{"level":"info","ts":1698080045.8507886,"logger":"cmd","msg":"Version","Go Version":"go1.18.8","GOOS":"linux","GOARCH":"amd64","ansible-operator":"v1.25.0","commit":"3d4eb4b2de4b68519c8828f2289c2014979ccf2a"}
{"level":"error","ts":1698080045.8509367,"logger":"cmd","msg":"Failed to get config.","error":"invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable","errorCauses":[{"error":"no configuration has been provided, try setting KUBERNETES_MASTER environment variable"}],"stacktrace":"github.com/operator-framework/operator-sdk/internal/cmd/ansible-operator/run.run\n\t/workspace/internal/cmd/ansible-operator/run/cmd.go:110\ngithub.com/operator-framework/operator-sdk/internal/cmd/ansible-operator/run.NewCmd.func1\n\t/workspace/internal/cmd/ansible-operator/run/cmd.go:80\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:920\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:1040\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:968\nmain.main\n\t/workspace/cmd/ansible-operator/main.go:40\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}

===RUN v1.68===
{"level":"info","ts":1698080046.0479991,"logger":"cmd","msg":"Version","Go Version":"go1.18.8","GOOS":"linux","GOARCH":"amd64","ansible-operator":"v1.25.0","commit":"3d4eb4b2de4b68519c8828f2289c2014979ccf2a"}
{"level":"error","ts":1698080046.0482552,"logger":"cmd","msg":"Failed to get config.","error":"invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable","errorCauses":[{"error":"no configuration has been provided, try setting KUBERNETES_MASTER environment variable"}],"stacktrace":"github.com/operator-framework/operator-sdk/internal/cmd/ansible-operator/run.run\n\t/workspace/internal/cmd/ansible-operator/run/cmd.go:110\ngithub.com/operator-framework/operator-sdk/internal/cmd/ansible-operator/run.NewCmd.func1\n\t/workspace/internal/cmd/ansible-operator/run/cmd.go:80\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:920\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:1040\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:968\nmain.main\n\t/workspace/cmd/ansible-operator/main.go:40\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}

===RUN v1.69===
{"level":"info","ts":"2023-10-23T16:54:06Z","logger":"cmd","msg":"Version","Go Version":"go1.18.10","GOOS":"linux","GOARCH":"amd64","ansible-operator":"v1.28.0","commit":"484013d1865c35df2bc5dfea0ab6ea6b434adefa"}
{"level":"error","ts":"2023-10-23T16:54:06Z","logger":"controller-runtime.client.config","msg":"unable to load in-cluster config","error":"unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined","stacktrace":"sigs.k8s.io/controller-runtime/pkg/client/config.loadConfig.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/client/config/config.go:133\nsigs.k8s.io/controller-runtime/pkg/client/config.loadConfig\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/client/config/config.go:155\nsigs.k8s.io/controller-runtime/pkg/client/config.GetConfigWithContext\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/client/config/config.go:97\nsigs.k8s.io/controller-runtime/pkg/client/config.GetConfig\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/client/config/config.go:77\ngithub.com/operator-framework/operator-sdk/internal/cmd/ansible-operator/run.run\n\t/workspace/internal/cmd/ansible-operator/run/cmd.go:108\ngithub.com/operator-framework/operator-sdk/internal/cmd/ansible-operator/run.NewCmd.func1\n\t/workspace/internal/cmd/ansible-operator/run/cmd.go:80\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968\nmain.main\n\t/workspace/cmd/ansible-operator/main.go:40\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
{"level":"error","ts":"2023-10-23T16:54:06Z","logger":"cmd","msg":"Failed to get config.","error":"invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable","errorCauses":[{"error":"no configuration has been provided, try setting KUBERNETES_MASTER environment variable"}],"stacktrace":"github.com/operator-framework/operator-sdk/internal/cmd/ansible-operator/run.run\n\t/workspace/internal/cmd/ansible-operator/run/cmd.go:110\ngithub.com/operator-framework/operator-sdk/internal/cmd/ansible-operator/run.NewCmd.func1\n\t/workspace/internal/cmd/ansible-operator/run/cmd.go:80\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968\nmain.main\n\t/workspace/cmd/ansible-operator/main.go:40\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}

===RUN v1.70===
{"level":"info","ts":"2023-10-23T16:54:06Z","logger":"cmd","msg":"Version","Go Version":"go1.18.10","GOOS":"linux","GOARCH":"amd64","ansible-operator":"v1.28.0","commit":"484013d1865c35df2bc5dfea0ab6ea6b434adefa"}
{"level":"error","ts":"2023-10-23T16:54:06Z","logger":"controller-runtime.client.config","msg":"unable to load in-cluster config","error":"unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined","stacktrace":"sigs.k8s.io/controller-runtime/pkg/client/config.loadConfig.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/client/config/config.go:133\nsigs.k8s.io/controller-runtime/pkg/client/config.loadConfig\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/client/config/config.go:155\nsigs.k8s.io/controller-runtime/pkg/client/config.GetConfigWithContext\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/client/config/config.go:97\nsigs.k8s.io/controller-runtime/pkg/client/config.GetConfig\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/client/config/config.go:77\ngithub.com/operator-framework/operator-sdk/internal/cmd/ansible-operator/run.run\n\t/workspace/internal/cmd/ansible-operator/run/cmd.go:108\ngithub.com/operator-framework/operator-sdk/internal/cmd/ansible-operator/run.NewCmd.func1\n\t/workspace/internal/cmd/ansible-operator/run/cmd.go:80\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968\nmain.main\n\t/workspace/cmd/ansible-operator/main.go:40\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
{"level":"error","ts":"2023-10-23T16:54:06Z","logger":"cmd","msg":"Failed to get config.","error":"invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable","errorCauses":[{"error":"no configuration has been provided, try setting KUBERNETES_MASTER environment variable"}],"stacktrace":"github.com/operator-framework/operator-sdk/internal/cmd/ansible-operator/run.run\n\t/workspace/internal/cmd/ansible-operator/run/cmd.go:110\ngithub.com/operator-framework/operator-sdk/internal/cmd/ansible-operator/run.NewCmd.func1\n\t/workspace/internal/cmd/ansible-operator/run/cmd.go:80\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968\nmain.main\n\t/workspace/cmd/ansible-operator/main.go:40\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
```

**Comment by jmazzitelli** [comment]
You will need to provide a step-by-step set of easy to run replication instructions (that doesn't utilize custom code, actions, scripts) so it is clear what it is you are doing to see the error and that kiali devs can use to replication this for further debugging. I assume you can just provide helm commands and helm values that can show this (like, "install the kiali operator via this helm command and then upgrade it using this helm command").

**Comment by mikebell90** [comment]
In the end I simply:

- deleted kiali 
- removed the operator
- cleans cm, secrets
- deleted crd

and reinstalled. At this point 1.75 works

My main feedback about this experience is reading and grokking ansible errors is not feasible for most operators, and should be reconsidered.

Tganks for your assistence

**Comment by mikebell90** [comment]
as for the quay.io. I swear I'm not crazy. Docker pull failed from my machine and then I went to the SAME web page you specify and they were gone a couple hours ago.
