### ISSUE TITLE
PFT graph page throws a console error when the user navigates to the graph from a details page

### ISSUE THREAD

**Issue by ferhoyos** [kiali/kiali#7802]
### Describe the bug

The console throws an error when the user navigates from a details page (application, service or workload) to the PFT traffic graph.

```
Uncaught TypeError: c.getElements is not a function
    at elems (GraphPFElems.tsx:651:1)
    at SummaryPanelGraph.render (SummaryPanelGraph.tsx:204:1)
    at finishClassComponent (react-dom.development.js:17485:1)
    at updateClassComponent (react-dom.development.js:17435:1)
    at beginWork (react-dom.development.js:19073:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at beginWork$1 (react-dom.development.js:23964:1)
    at performUnitOfWork (react-dom.development.js:22776:1)
```

The issue is related with summaryTarget redux property (`state.graph.summaryData.summaryTarget`), whose value seems to be updated when the user access a details page and this value is not suitable to the PFT traffic graph. 

### Expected Behavior

The PFT graph should not throw any console error.

### What are the steps to reproduce this bug?

1. Go to any details page (application, service or workload)
2. From the details page navigates to the PFT traffic graph
3. Verify that an error appears in the browser console

![image](https://github.com/user-attachments/assets/d524970e-f856-45db-b5c3-aec11cd25783)

### Environment

- **Kiali version:** master
- **Istio version:** 1.23.2
- **Kubernetes impl:** kind
- **Kubernetes version:** 1.27

**Comment by jshaughn** [comment]
I could not reproduce this using 2.0 master.  Maybe not happening with PF as the default?

**Comment by jshaughn** [comment]
@ferhoyos Are you still seeing this?

**Comment by ferhoyos** [comment]
@jshaughn Today I was focused on OSSMC and I have not tested again with the latest master branch. I will check it tomorrow.

**Comment by ferhoyos** [comment]
@jshaughn I cannot reproduce the issue now. Maybe it was fixed by setting PF as the default or by other PRs related to PFT. Closing the issue.
